# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_tax_types_id_patch_request_tax_type import RestV10TaxTypesIdPatchRequestTaxType

class TestRestV10TaxTypesIdPatchRequestTaxType(unittest.TestCase):
    """RestV10TaxTypesIdPatchRequestTaxType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10TaxTypesIdPatchRequestTaxType:
        """Test RestV10TaxTypesIdPatchRequestTaxType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10TaxTypesIdPatchRequestTaxType`
        """
        model = RestV10TaxTypesIdPatchRequestTaxType()
        if include_optional:
            return RestV10TaxTypesIdPatchRequestTaxType(
                description = 'Goods and Services Tax',
                name = 'GST',
                origin_data = '{ parent_ids: [1,2] }',
                origin_id = '1VT-33778-013'
            )
        else:
            return RestV10TaxTypesIdPatchRequestTaxType(
        )
        """

    def testRestV10TaxTypesIdPatchRequestTaxType(self):
        """Test RestV10TaxTypesIdPatchRequestTaxType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
