# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_get_default_response import RestV10ProjectsGetDefaultResponse

class TestRestV10ProjectsGetDefaultResponse(unittest.TestCase):
    """RestV10ProjectsGetDefaultResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsGetDefaultResponse:
        """Test RestV10ProjectsGetDefaultResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsGetDefaultResponse`
        """
        model = RestV10ProjectsGetDefaultResponse()
        if include_optional:
            return RestV10ProjectsGetDefaultResponse(
                error = procore_sdk.models.rest_v10_projects_get_default_response_error.RestV10ProjectsGet_default_response_error(
                    code = '', 
                    message = '', 
                    details = [
                        procore_sdk.models.rest_v10_projects_get_default_response_error_details_inner.RestV10ProjectsGet_default_response_error_details_inner(
                            code = '', 
                            message = '', 
                            source = '', )
                        ], )
            )
        else:
            return RestV10ProjectsGetDefaultResponse(
                error = procore_sdk.models.rest_v10_projects_get_default_response_error.RestV10ProjectsGet_default_response_error(
                    code = '', 
                    message = '', 
                    details = [
                        procore_sdk.models.rest_v10_projects_get_default_response_error_details_inner.RestV10ProjectsGet_default_response_error_details_inner(
                            code = '', 
                            message = '', 
                            source = '', )
                        ], ),
        )
        """

    def testRestV10ProjectsGetDefaultResponse(self):
        """Test RestV10ProjectsGetDefaultResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
