# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_change_order_requests_post_request_change_order import RestV10ChangeOrderRequestsPostRequestChangeOrder

class TestRestV10ChangeOrderRequestsPostRequestChangeOrder(unittest.TestCase):
    """RestV10ChangeOrderRequestsPostRequestChangeOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ChangeOrderRequestsPostRequestChangeOrder:
        """Test RestV10ChangeOrderRequestsPostRequestChangeOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ChangeOrderRequestsPostRequestChangeOrder`
        """
        model = RestV10ChangeOrderRequestsPostRequestChangeOrder()
        if include_optional:
            return RestV10ChangeOrderRequestsPostRequestChangeOrder(
                change_order_package_id = 98762,
                description = '<p>Freezer slab replacement</p>',
                due_date = '2016-11-23T21:39:40Z',
                grand_total = 34535,
                invoiced_date = 'Tue Aug 22 00:00:00 UTC 2017',
                origin_data = 'OD-2398273424',
                origin_id = '459247544',
                paid_date = 'Fri Aug 25 00:00:00 UTC 2017',
                schedule_impact_amount = 2,
                status = 'draft',
                title = 'Concrete freezer slab'
            )
        else:
            return RestV10ChangeOrderRequestsPostRequestChangeOrder(
        )
        """

    def testRestV10ChangeOrderRequestsPostRequestChangeOrder(self):
        """Test RestV10ChangeOrderRequestsPostRequestChangeOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
