# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_companies_company_id_managed_equipment_types_bulk_update_patch_request import RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest

class TestRestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest(unittest.TestCase):
    """RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest:
        """Test RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest`
        """
        model = RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest()
        if include_optional:
            return RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest(
                managed_equipment_type = procore_sdk.models.rest_v10_companies_company_id_managed_equipment_types_bulk_update_patch_request_managed_equipment_type.RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatch_request_managed_equipment_type(
                    is_active = True, 
                    managed_equipment_category_id = 534, )
            )
        else:
            return RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest(
                managed_equipment_type = procore_sdk.models.rest_v10_companies_company_id_managed_equipment_types_bulk_update_patch_request_managed_equipment_type.RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatch_request_managed_equipment_type(
                    is_active = True, 
                    managed_equipment_category_id = 534, ),
        )
        """

    def testRestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest(self):
        """Test RestV10CompaniesCompanyIdManagedEquipmentTypesBulkUpdatePatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
