# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.core_project_project_demos_api import CoreProjectProjectDemosApi


class TestCoreProjectProjectDemosApi(unittest.TestCase):
    """CoreProjectProjectDemosApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoreProjectProjectDemosApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_projects_project_id_recent_activity_get(self) -> None:
        """Test case for rest_v10_projects_project_id_recent_activity_get

        List Recent Activity Items
        """
        pass


if __name__ == '__main__':
    unittest.main()
