# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_daily_logs_clones_post201_response_notes_log_created_by import RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy

class TestRestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy(unittest.TestCase):
    """RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy:
        """Test RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy`
        """
        model = RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy()
        if include_optional:
            return RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy(
                id = 3,
                login = 'carl.contractor@example.com',
                name = ''
            )
        else:
            return RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy(
        )
        """

    def testRestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy(self):
        """Test RestV10ProjectsProjectIdDailyLogsClonesPost201ResponseNotesLogCreatedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
