# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.project_management_models_bim_model_revision_objects_api import ProjectManagementModelsBIMModelRevisionObjectsApi


class TestProjectManagementModelsBIMModelRevisionObjectsApi(unittest.TestCase):
    """ProjectManagementModelsBIMModelRevisionObjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectManagementModelsBIMModelRevisionObjectsApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_bim_model_revisions_id_objects_get(self) -> None:
        """Test case for rest_v10_bim_model_revisions_id_objects_get

        List BIM Model Revision objects
        """
        pass


if __name__ == '__main__':
    unittest.main()
