# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body68_meeting_attendee_record import Body68MeetingAttendeeRecord

class TestBody68MeetingAttendeeRecord(unittest.TestCase):
    """Body68MeetingAttendeeRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body68MeetingAttendeeRecord:
        """Test Body68MeetingAttendeeRecord
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body68MeetingAttendeeRecord`
        """
        model = Body68MeetingAttendeeRecord()
        if include_optional:
            return Body68MeetingAttendeeRecord(
                status = 'Present',
                login_information_id = 999
            )
        else:
            return Body68MeetingAttendeeRecord(
        )
        """

    def testBody68MeetingAttendeeRecord(self):
        """Test Body68MeetingAttendeeRecord"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
