# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.construction_financials_budget_budget_detail_columns_api import ConstructionFinancialsBudgetBudgetDetailColumnsApi


class TestConstructionFinancialsBudgetBudgetDetailColumnsApi(unittest.TestCase):
    """ConstructionFinancialsBudgetBudgetDetailColumnsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConstructionFinancialsBudgetBudgetDetailColumnsApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_budget_views_budget_view_id_budget_detail_columns_get(self) -> None:
        """Test case for rest_v10_budget_views_budget_view_id_budget_detail_columns_get

        List Budget Detail Columns
        """
        pass


if __name__ == '__main__':
    unittest.main()
