# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.punch_item6_created_by import PunchItem6CreatedBy

class TestPunchItem6CreatedBy(unittest.TestCase):
    """PunchItem6CreatedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PunchItem6CreatedBy:
        """Test PunchItem6CreatedBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PunchItem6CreatedBy`
        """
        model = PunchItem6CreatedBy()
        if include_optional:
            return PunchItem6CreatedBy(
                id = 1738090,
                name = 'John Doe',
                login = 'johndoe@example.com'
            )
        else:
            return PunchItem6CreatedBy(
        )
        """

    def testPunchItem6CreatedBy(self):
        """Test PunchItem6CreatedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
