# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_companies_company_id_work_breakdown_structure_segments_post_request import RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest

class TestRestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest(unittest.TestCase):
    """RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest:
        """Test RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest`
        """
        model = RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest()
        if include_optional:
            return RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest(
                segment = procore_sdk.models.segment.Segment(
                    name = 'Phase', 
                    project_can_modify_origin_project = True, 
                    project_can_delete_origin_company = True, 
                    structure = 'flat', )
            )
        else:
            return RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest(
                segment = procore_sdk.models.segment.Segment(
                    name = 'Phase', 
                    project_can_modify_origin_project = True, 
                    project_can_delete_origin_company = True, 
                    structure = 'flat', ),
        )
        """

    def testRestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest(self):
        """Test RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
