# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.department_body import DepartmentBody

class TestDepartmentBody(unittest.TestCase):
    """DepartmentBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DepartmentBody:
        """Test DepartmentBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DepartmentBody`
        """
        model = DepartmentBody()
        if include_optional:
            return DepartmentBody(
                company_id = 56,
                department = procore_sdk.models.department.Department(
                    name = 'Department A', 
                    origin_data = 'OD-1234', 
                    origin_id = 'OI-5678', )
            )
        else:
            return DepartmentBody(
                company_id = 56,
                department = procore_sdk.models.department.Department(
                    name = 'Department A', 
                    origin_data = 'OD-1234', 
                    origin_id = 'OI-5678', ),
        )
        """

    def testDepartmentBody(self):
        """Test DepartmentBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
