# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_plan_revision_logs_get200_response_inner import RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner

class TestRestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner(unittest.TestCase):
    """RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner:
        """Test RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner`
        """
        model = RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner()
        if include_optional:
            return RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner(
                id = 333675,
                category = 'Plan Revision category',
                comments = 'Plan Revision comments',
                var_date = 'Thu May 19 00:00:00 UTC 2016',
                datetime = '2016-05-19T12:00Z',
                deleted_at = '2017-07-29T21:39:40Z',
                plan_number = '3plan#',
                position = 142143,
                revision = 'Revision',
                title = 'Plan Revision title',
                created_by = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                    id = 160586, 
                    login = 'carl.contractor@example.com', 
                    name = 'Carl Contractor', ),
                attachments = [
                    procore_sdk.models.rest_v10_companies_company_id_workflow_permanent_logs_get_200_response_inner_attachments_inner.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet_200_response_inner_attachments_inner(
                        id = 56, 
                        name = '', 
                        url = '', 
                        filename = '', )
                    ]
            )
        else:
            return RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner(
        )
        """

    def testRestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner(self):
        """Test RestV10ProjectsProjectIdPlanRevisionLogsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
