# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_companies_company_id_action_plans_plan_template_item_assignees_bulk_update_patch_request import RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest

class TestRestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest(unittest.TestCase):
    """RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest:
        """Test RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest`
        """
        model = RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest()
        if include_optional:
            return RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest(
                plan_template_item_assignees = [
                    procore_sdk.models.action_plan_item_assignees_inner.Action_Plan_Item_Assignees_inner(
                        id = 123, 
                        party_id = 27, 
                        verification_method_id = 1, 
                        role = 'architect', )
                    ]
            )
        else:
            return RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest(
                plan_template_item_assignees = [
                    procore_sdk.models.action_plan_item_assignees_inner.Action_Plan_Item_Assignees_inner(
                        id = 123, 
                        party_id = 27, 
                        verification_method_id = 1, 
                        role = 'architect', )
                    ],
        )
        """

    def testRestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest(self):
        """Test RestV10CompaniesCompanyIdActionPlansPlanTemplateItemAssigneesBulkUpdatePatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
