# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body124_bim_view_folder import Body124BimViewFolder

class TestBody124BimViewFolder(unittest.TestCase):
    """Body124BimViewFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body124BimViewFolder:
        """Test Body124BimViewFolder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body124BimViewFolder`
        """
        model = Body124BimViewFolder()
        if include_optional:
            return Body124BimViewFolder(
                name = 'Mechanical',
                parent_id = 168,
                bim_file_id = 196
            )
        else:
            return Body124BimViewFolder(
                name = 'Mechanical',
                bim_file_id = 196,
        )
        """

    def testBody124BimViewFolder(self):
        """Test Body124BimViewFolder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
