# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.project_management_coordination_issues_coordination_issue_potential_assignees_api import ProjectManagementCoordinationIssuesCoordinationIssuePotentialAssigneesApi


class TestProjectManagementCoordinationIssuesCoordinationIssuePotentialAssigneesApi(unittest.TestCase):
    """ProjectManagementCoordinationIssuesCoordinationIssuePotentialAssigneesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectManagementCoordinationIssuesCoordinationIssuePotentialAssigneesApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_coordination_issues_assignees_get(self) -> None:
        """Test case for rest_v10_coordination_issues_assignees_get

        List Coordination Issue Assignable Users
        """
        pass


if __name__ == '__main__':
    unittest.main()
