# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_schedule_lookahead_tasks_post201_response import RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response

class TestRestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response(unittest.TestCase):
    """RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response:
        """Test RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response`
        """
        model = RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response()
        if include_optional:
            return RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response(
                id = 56,
                project_id = 156293,
                company_id = 5499,
                lookahead_id = 8,
                task_id = 2401832,
                created_at = '2019-09-20T00:00Z',
                created_by_id = 12,
                parent_id = 1,
                name = 'Interior',
                start_date = '2019-09-20',
                end_date = '2019-09-30',
                row_number = 2,
                critical_path = False,
                comment = '',
                activity_id = '1000435',
                wbs = '1.2',
                assignee_ids = [
                    56
                    ],
                resource_ids = [
                    56
                    ],
                vendor_ids = [
                    56
                    ],
                segments = [
                    procore_sdk.models.rest_v10_projects_project_id_schedule_lookahead_tasks_post_201_response_segments_inner.RestV10ProjectsProjectIdScheduleLookaheadTasksPost_201_response_segments_inner(
                        date = 'Wed Feb 12 00:00:00 UTC 2020', 
                        status = 'complete', )
                    ],
                resources = [
                    null
                    ]
            )
        else:
            return RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response(
        )
        """

    def testRestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response(self):
        """Test RestV10ProjectsProjectIdScheduleLookaheadTasksPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
