# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_field_production_report_get200_response_inner import RestV10FieldProductionReportGet200ResponseInner

class TestRestV10FieldProductionReportGet200ResponseInner(unittest.TestCase):
    """RestV10FieldProductionReportGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10FieldProductionReportGet200ResponseInner:
        """Test RestV10FieldProductionReportGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10FieldProductionReportGet200ResponseInner`
        """
        model = RestV10FieldProductionReportGet200ResponseInner()
        if include_optional:
            return RestV10FieldProductionReportGet200ResponseInner(
                cost_code_id = 302323,
                cost_code = '03 - Instructions',
                budgeted_hours = 100,
                actual_hours = 46.5,
                remaining_hours = 53.5,
                hours_utilization = '46.5%',
                projected_hours_at_completion = 108.5,
                earned_hours = 30,
                budgeted_quantity = 100,
                actual_quantity = 30,
                remaining_quantities = 70,
                unit_of_measure = 'ea',
                percent_complete = '30%',
                budgeted_production_rate = 1,
                actual_production_rate = 0.65,
                production_rate_variance = -0.35,
                is_budgeted = 'Yes',
                sub_job_name = 'Building 1',
                sub_job_id = 392483
            )
        else:
            return RestV10FieldProductionReportGet200ResponseInner(
        )
        """

    def testRestV10FieldProductionReportGet200ResponseInner(self):
        """Test RestV10FieldProductionReportGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
