# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.field_productivity_field_production_report_field_production_report_api import FieldProductivityFieldProductionReportFieldProductionReportApi


class TestFieldProductivityFieldProductionReportFieldProductionReportApi(unittest.TestCase):
    """FieldProductivityFieldProductionReportFieldProductionReportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FieldProductivityFieldProductionReportFieldProductionReportApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_field_production_report_get(self) -> None:
        """Test case for rest_v10_field_production_report_get

        List Field Production Report Summary
        """
        pass


if __name__ == '__main__':
    unittest.main()
