# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_rfis_post201_response import RestV10ProjectsProjectIdRfisPost201Response

class TestRestV10ProjectsProjectIdRfisPost201Response(unittest.TestCase):
    """RestV10ProjectsProjectIdRfisPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdRfisPost201Response:
        """Test RestV10ProjectsProjectIdRfisPost201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdRfisPost201Response`
        """
        model = RestV10ProjectsProjectIdRfisPost201Response()
        if include_optional:
            return RestV10ProjectsProjectIdRfisPost201Response(
                accepted = False,
                ball_in_court_role = 'assignees',
                custom_textfield_1 = procore_sdk.models.rest_v10_projects_project_id_rfis_post_201_response_all_of_custom_textfield_1.RestV10ProjectsProjectIdRfisPost_201_response_allOf_custom_textfield_1(
                    label = '', 
                    value = '', ),
                custom_textfield_2 = procore_sdk.models.rest_v10_projects_project_id_rfis_post_201_response_all_of_custom_textfield_2.RestV10ProjectsProjectIdRfisPost_201_response_allOf_custom_textfield_2(
                    label = '', 
                    value = '', ),
                distribution_list = [
                    null
                    ],
                draft = False,
                drawing_ids = [
                    999
                    ],
                drawing_number = '107.3D',
                questions = [
                    procore_sdk.models.rest_v10_projects_project_id_rfis_post_201_response_all_of_questions_inner.RestV10ProjectsProjectIdRfisPost_201_response_allOf_questions_inner(
                        id = 56, 
                        question_date = '2016-08-02T20:49:35Z', 
                        plain_text_body = 'Are the items listed on Schedule C acceptable?', 
                        rich_text_body = '<p>Are the items listed on Schedule C acceptable?</p>', 
                        created_by = 'Joseph Shabadoo', 
                        attachments = [
                            procore_sdk.models.rest_v10_companies_company_id_workflow_permanent_logs_get_200_response_inner_attachments_inner.RestV10CompaniesCompanyIdWorkflowPermanentLogsGet_200_response_inner_attachments_inner(
                                id = 56, 
                                name = '', 
                                url = '', 
                                filename = '', )
                            ], 
                        answers = [
                            procore_sdk.models.rest_v10_projects_project_id_rfis_post_201_response_all_of_questions_inner_answers_inner.RestV10ProjectsProjectIdRfisPost_201_response_allOf_questions_inner_answers_inner(
                                id = 999, 
                                official = True, 
                                answer_date = '2016-08-29T14:37:22Z', 
                                plain_text_body = 'No, they need to follow the guidelines on Schedule D', 
                                rich_text_body = '<p>No, they need to follow the guidelines on Schedule D</p>', 
                                created_by = 'Jane Doe', 
                                created_by_id = 42, )
                            ], )
                    ],
                specification_section = procore_sdk.models.rest_v10_projects_project_id_rfis_post_201_response_all_of_specification_section.RestV10ProjectsProjectIdRfisPost_201_response_allOf_specification_section(
                    id = 56, 
                    description = '', 
                    number = '', ),
                custom_fields = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields(
                    custom_field_%{custom_field_string_definition_id} = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields_custom_field___custom_field_string_definition_id_.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields_custom_field___custom_field_string_definition_id_(
                        data_type = 'string', 
                        value = 'custom field value', ), 
                    custom_field_%{custom_field_decimal_definition_id} = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields_custom_field___custom_field_decimal_definition_id_.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields_custom_field___custom_field_decimal_definition_id_(
                        data_type = 'decimal', 
                        value = 2.2, ), 
                    custom_field_%{custom_field_boolean_definition_id} = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields_custom_field___custom_field_boolean_definition_id_.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields_custom_field___custom_field_boolean_definition_id_(
                        data_type = 'boolean', 
                        value = True, ), 
                    custom_field_%{custom_field_lov_entry_definition_id} = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields_custom_field___custom_field_lov_entry_definition_id_.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields_custom_field___custom_field_lov_entry_definition_id_(
                        data_type = 'lov_entry', 
                        value = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields_custom_field___custom_field_lov_entry_definition_id__value.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields_custom_field___custom_field_lov_entry_definition_id__value(
                            id = 1, 
                            label = 'Open', ), ), 
                    custom_field_%{custom_field_lov_entries_definition_id} = procore_sdk.models.rest_v11_projects_project_id_recycle_bin_incidents_witness_statements_get_200_response_inner_custom_fields_custom_field___custom_field_lov_entries_definition_id_.RestV11ProjectsProjectIdRecycleBinIncidentsWitnessStatementsGet_200_response_inner_custom_fields_custom_field___custom_field_lov_entries_definition_id_(
                        data_type = 'lov_entries', ), ),
                id = 999,
                assignee = None,
                assignees = [
                    null
                    ],
                ball_in_court = None,
                ball_in_courts = [
                    null
                    ],
                cost_code = procore_sdk.models.timecard_entry_full_cost_code.TimecardEntry_full_cost_code(
                    id = 12345, 
                    name = 'Earthwork', ),
                cost_impact = procore_sdk.models.rest_v10_projects_project_id_rfis_get_200_response_inner_all_of_cost_impact.RestV10ProjectsProjectIdRfisGet_200_response_inner_allOf_cost_impact(
                    status = 'yes_known', 
                    value = 12039.55, ),
                created_at = '2016-08-23T15:23:57Z',
                deleted = True,
                deleted_at = '2016-08-23T15:23:57Z',
                due_date = 'Wed Jan 18 00:00:00 UTC 2017',
                initiated_at = '2016-08-23T15:23:57Z',
                location = procore_sdk.models.location.Location(
                    id = 15504, 
                    name = '1space>1 space', 
                    node_name = '1 space', 
                    parent_id = 788866, 
                    created_at = '2016-08-01T23:33:54Z', 
                    updated_at = '2016-08-01T23:33:54Z', ),
                full_number = 'C-1477',
                number = '1477',
                prefix = 'C',
                private = True,
                received_from = None,
                reference = 'Schedule C',
                responsible_contractor = procore_sdk.models.rest_v10_projects_project_id_waste_logs_get_200_response_inner_vendor.RestV10ProjectsProjectIdWasteLogsGet_200_response_inner_vendor(
                    id = 161072, 
                    name = 'SID Architecture', ),
                rfi_manager = None,
                schedule_impact = procore_sdk.models.rest_v10_projects_project_id_rfis_get_200_response_inner_all_of_schedule_impact.RestV10ProjectsProjectIdRfisGet_200_response_inner_allOf_schedule_impact(
                    status = 'yes_known', 
                    value = 14, ),
                status = 'open',
                translated_status = 'Abierto',
                subject = 'Specifications [99 14.44B]',
                time_resolved = '2017-01-12T17:09:15Z',
                updated_at = '2012-10-24T21:39:40Z'
            )
        else:
            return RestV10ProjectsProjectIdRfisPost201Response(
        )
        """

    def testRestV10ProjectsProjectIdRfisPost201Response(self):
        """Test RestV10ProjectsProjectIdRfisPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
