# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_companies_company_id_app_configurations_post_request import RestV10CompaniesCompanyIdAppConfigurationsPostRequest

class TestRestV10CompaniesCompanyIdAppConfigurationsPostRequest(unittest.TestCase):
    """RestV10CompaniesCompanyIdAppConfigurationsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CompaniesCompanyIdAppConfigurationsPostRequest:
        """Test RestV10CompaniesCompanyIdAppConfigurationsPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CompaniesCompanyIdAppConfigurationsPostRequest`
        """
        model = RestV10CompaniesCompanyIdAppConfigurationsPostRequest()
        if include_optional:
            return RestV10CompaniesCompanyIdAppConfigurationsPostRequest(
                applies_to_all_projects = True,
                applies_to_company = True,
                app_installation_id = 3559,
                company_id = 56,
                instance_configuration = {"resource_id":1287},
                project_ids = [
                    56
                    ],
                title = 'Drone Deploy Project Configurations'
            )
        else:
            return RestV10CompaniesCompanyIdAppConfigurationsPostRequest(
                app_installation_id = 3559,
                company_id = 56,
                instance_configuration = {"resource_id":1287},
                title = 'Drone Deploy Project Configurations',
        )
        """

    def testRestV10CompaniesCompanyIdAppConfigurationsPostRequest(self):
        """Test RestV10CompaniesCompanyIdAppConfigurationsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
