# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_meetings_get200_response_inner import RestV10MeetingsGet200ResponseInner

class TestRestV10MeetingsGet200ResponseInner(unittest.TestCase):
    """RestV10MeetingsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10MeetingsGet200ResponseInner:
        """Test RestV10MeetingsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10MeetingsGet200ResponseInner`
        """
        model = RestV10MeetingsGet200ResponseInner()
        if include_optional:
            return RestV10MeetingsGet200ResponseInner(
                group_title = 'Jon's Meeting',
                meetings = [
                    procore_sdk.models.rest_v10_meetings_get_200_response_inner_meetings_inner.RestV10MeetingsGet_200_response_inner_meetings_inner(
                        id = 82593, 
                        title = 'Jon's Meeting', 
                        position = 1, 
                        created_by_id = 1, 
                        description = 'Stuff is going to go down aka ticket eating', 
                        mode = 'minutes', 
                        meeting_date = 'Mon Apr 14 00:00:00 UTC 2014', 
                        parent_id = 88835, 
                        location = 'Office 123', 
                        meeting_topics_count = 5, 
                        occurred = True, 
                        is_private = True, 
                        created_at = '2021-07-23T10:00Z', 
                        updated_at = '2021-07-23T10:00Z', )
                    ]
            )
        else:
            return RestV10MeetingsGet200ResponseInner(
        )
        """

    def testRestV10MeetingsGet200ResponseInner(self):
        """Test RestV10MeetingsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
