# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.construction_financials_change_orders_prime_change_orders_api import ConstructionFinancialsChangeOrdersPrimeChangeOrdersApi


class TestConstructionFinancialsChangeOrdersPrimeChangeOrdersApi(unittest.TestCase):
    """ConstructionFinancialsChangeOrdersPrimeChangeOrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConstructionFinancialsChangeOrdersPrimeChangeOrdersApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_projects_project_id_prime_change_orders_get(self) -> None:
        """Test case for rest_v10_projects_project_id_prime_change_orders_get

        Show All Prime Change Orders
        """
        pass

    def test_rest_v10_projects_project_id_prime_change_orders_id_delete(self) -> None:
        """Test case for rest_v10_projects_project_id_prime_change_orders_id_delete

        Delete Prime Change Order
        """
        pass

    def test_rest_v10_projects_project_id_prime_change_orders_id_get(self) -> None:
        """Test case for rest_v10_projects_project_id_prime_change_orders_id_get

        Show Prime Change Order
        """
        pass

    def test_rest_v10_projects_project_id_prime_change_orders_id_patch(self) -> None:
        """Test case for rest_v10_projects_project_id_prime_change_orders_id_patch

        Update Prime Change Order
        """
        pass

    def test_rest_v10_projects_project_id_prime_change_orders_post(self) -> None:
        """Test case for rest_v10_projects_project_id_prime_change_orders_post

        Create Prime Change Order
        """
        pass


if __name__ == '__main__':
    unittest.main()
