# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body126_bim_plan_one_of import Body126BimPlanOneOf

class TestBody126BimPlanOneOf(unittest.TestCase):
    """Body126BimPlanOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body126BimPlanOneOf:
        """Test Body126BimPlanOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body126BimPlanOneOf`
        """
        model = Body126BimPlanOneOf()
        if include_optional:
            return Body126BimPlanOneOf(
                bim_level_id = 16,
                sheet_map_start = procore_sdk.models.body_125_bim_plan_one_of_sheet_map_start.Body_125_bim_plan_oneOf_sheet_map_start(
                    x = 6.24, 
                    y = 12.48, ),
                sheet_map_end = procore_sdk.models.body_125_bim_plan_one_of_sheet_map_start.Body_125_bim_plan_oneOf_sheet_map_start(
                    x = 6.24, 
                    y = 12.48, ),
                model_map_start = procore_sdk.models.body_125_bim_plan_one_of_model_map_start.Body_125_bim_plan_oneOf_model_map_start(
                    x = 6.24, 
                    y = 12.48, 
                    z = 24.96, ),
                model_map_end = procore_sdk.models.body_125_bim_plan_one_of_model_map_start.Body_125_bim_plan_oneOf_model_map_start(
                    x = 6.24, 
                    y = 12.48, 
                    z = 24.96, )
            )
        else:
            return Body126BimPlanOneOf(
                bim_level_id = 16,
        )
        """

    def testBody126BimPlanOneOf(self):
        """Test Body126BimPlanOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
