# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.checklist_inspection_attachment import ChecklistInspectionAttachment

class TestChecklistInspectionAttachment(unittest.TestCase):
    """ChecklistInspectionAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChecklistInspectionAttachment:
        """Test ChecklistInspectionAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChecklistInspectionAttachment`
        """
        model = ChecklistInspectionAttachment()
        if include_optional:
            return ChecklistInspectionAttachment(
                id = 5324,
                url = 'http://www.example.com/',
                thumbnail_url = 'http://www.example.com/',
                name = 'january_receipt_copy.jpg',
                filename = 'january_receipt_copy.jpg',
                content_type = 'application/pdf',
                viewable_document_id = 492
            )
        else:
            return ChecklistInspectionAttachment(
        )
        """

    def testChecklistInspectionAttachment(self):
        """Test ChecklistInspectionAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
