# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.project_management_coordination_issues_coordination_issue_status_totals_api import ProjectManagementCoordinationIssuesCoordinationIssueStatusTotalsApi


class TestProjectManagementCoordinationIssuesCoordinationIssueStatusTotalsApi(unittest.TestCase):
    """ProjectManagementCoordinationIssuesCoordinationIssueStatusTotalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectManagementCoordinationIssuesCoordinationIssueStatusTotalsApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_coordination_issues_status_total_get(self) -> None:
        """Test case for rest_v10_coordination_issues_status_total_get

        Show Coordination Issue Count by Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
