# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_companies_company_id_hazards_bulk_update_patch_request_hazard import RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard

class TestRestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard(unittest.TestCase):
    """RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard:
        """Test RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard`
        """
        model = RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard()
        if include_optional:
            return RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard(
                ids = [
                    435
                    ],
                active = True
            )
        else:
            return RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard(
        )
        """

    def testRestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard(self):
        """Test RestV10CompaniesCompanyIdHazardsBulkUpdatePatchRequestHazard"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
