# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.checklist_response1 import ChecklistResponse1

class TestChecklistResponse1(unittest.TestCase):
    """ChecklistResponse1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChecklistResponse1:
        """Test ChecklistResponse1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChecklistResponse1`
        """
        model = ChecklistResponse1()
        if include_optional:
            return ChecklistResponse1(
                id = 1,
                name = 'Safe - Knowledge',
                status = 'non_conforming',
                item_status_id = 1
            )
        else:
            return ChecklistResponse1(
        )
        """

    def testChecklistResponse1(self):
        """Test ChecklistResponse1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
