# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_budget_views_get200_response_inner_created_by import RestV10BudgetViewsGet200ResponseInnerCreatedBy

class TestRestV10BudgetViewsGet200ResponseInnerCreatedBy(unittest.TestCase):
    """RestV10BudgetViewsGet200ResponseInnerCreatedBy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10BudgetViewsGet200ResponseInnerCreatedBy:
        """Test RestV10BudgetViewsGet200ResponseInnerCreatedBy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10BudgetViewsGet200ResponseInnerCreatedBy`
        """
        model = RestV10BudgetViewsGet200ResponseInnerCreatedBy()
        if include_optional:
            return RestV10BudgetViewsGet200ResponseInnerCreatedBy(
                id = 1234,
                name = 'John Doe',
                login = 'john.doe@example.com'
            )
        else:
            return RestV10BudgetViewsGet200ResponseInnerCreatedBy(
        )
        """

    def testRestV10BudgetViewsGet200ResponseInnerCreatedBy(self):
        """Test RestV10BudgetViewsGet200ResponseInnerCreatedBy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
