# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v11_projects_project_id_schedule_requested_changes_review_patch_request import RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest

class TestRestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest(unittest.TestCase):
    """RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest:
        """Test RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest`
        """
        model = RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest()
        if include_optional:
            return RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest(
                requested_changes = [
                    procore_sdk.models.rest_v11_projects_project_id_schedule_requested_changes_review_patch_request_requested_changes_inner.RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatch_request_requested_changes_inner(
                        id = 1, 
                        approved = True, 
                        disposition_reason = 'Looks reasonable', )
                    ]
            )
        else:
            return RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest(
        )
        """

    def testRestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest(self):
        """Test RestV11ProjectsProjectIdScheduleRequestedChangesReviewPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
