# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.company_user1 import CompanyUser1

class TestCompanyUser1(unittest.TestCase):
    """CompanyUser1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CompanyUser1:
        """Test CompanyUser1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CompanyUser1`
        """
        model = CompanyUser1()
        if include_optional:
            return CompanyUser1(
                first_name = '',
                last_name = '',
                job_title = '',
                address = '',
                city = '',
                zip = '',
                business_phone = '',
                business_phone_extension = 56,
                mobile_phone = '',
                fax_number = '',
                email_address = '',
                email_signature = '',
                is_active = True,
                is_employee = True,
                employee_id = '',
                notes = '',
                country_code = '',
                state_code = '',
                initials = '',
                origin_id = '',
                origin_data = 'OD-3483830-2',
                vendor_id = 56,
                default_permission_template_id = 56,
                company_permission_template_id = 56,
                work_classification_id = 56,
                avatar = '',
                bid_contact = True
            )
        else:
            return CompanyUser1(
                last_name = '',
                email_address = '',
        )
        """

    def testCompanyUser1(self):
        """Test CompanyUser1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
