# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.timecard_entry4 import TimecardEntry4

class TestTimecardEntry4(unittest.TestCase):
    """TimecardEntry4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimecardEntry4:
        """Test TimecardEntry4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimecardEntry4`
        """
        model = TimecardEntry4()
        if include_optional:
            return TimecardEntry4(
                var_date = 'Sun May 19 00:00:00 UTC 2019',
                hours = '8.0',
                lunch_time = '60',
                time_in = '2019-05-19T07:08:00Z',
                time_out = '2019-05-19T07:17:00Z',
                billable = True,
                description = 'No injuries today.',
                timecard_time_type_id = 10,
                location_id = 21,
                cost_code_id = 90,
                set_timecard_time_type_automatically = True,
                sub_job_id = 11,
                party_id = 87,
                crew_id = 92,
                procore_signature_id = 980,
                timesheet_id = 41823,
                clock_in_id = 345,
                clock_out_id = 642,
                clock_in_time = '2020-03-24T04:14:06Z',
                clock_out_time = '2020-03-24T05:14:22Z',
                approval_status = 'approved',
                origin_id = 23423,
                origin_data = '{'example':'related data'}',
                line_item_type_id = 13
            )
        else:
            return TimecardEntry4(
                var_date = 'Sun May 19 00:00:00 UTC 2019',
        )
        """

    def testTimecardEntry4(self):
        """Test TimecardEntry4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
