# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.field_productivity_timecard_gps_positions_api import FieldProductivityTimecardGpsPositionsApi


class TestFieldProductivityTimecardGpsPositionsApi(unittest.TestCase):
    """FieldProductivityTimecardGpsPositionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FieldProductivityTimecardGpsPositionsApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_companies_company_id_gps_positions_get(self) -> None:
        """Test case for rest_v10_companies_company_id_gps_positions_get

        List Gps Positions
        """
        pass

    def test_rest_v10_companies_company_id_gps_positions_id_get(self) -> None:
        """Test case for rest_v10_companies_company_id_gps_positions_id_get

        Show Gps Position
        """
        pass

    def test_rest_v10_companies_company_id_gps_positions_post(self) -> None:
        """Test case for rest_v10_companies_company_id_gps_positions_post

        Create Gps Position
        """
        pass


if __name__ == '__main__':
    unittest.main()
