# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body76 import Body76

class TestBody76(unittest.TestCase):
    """Body76 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body76:
        """Test Body76
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body76`
        """
        model = Body76()
        if include_optional:
            return Body76(
                instruction_type = procore_sdk.models.instruction_type.Instruction Type(
                    name = 'Owner Instruction', )
            )
        else:
            return Body76(
                instruction_type = procore_sdk.models.instruction_type.Instruction Type(
                    name = 'Owner Instruction', ),
        )
        """

    def testBody76(self):
        """Test Body76"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
