# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_bim_plans_get200_response_inner_all_of_model_map_start import RestV10BimPlansGet200ResponseInnerAllOfModelMapStart

class TestRestV10BimPlansGet200ResponseInnerAllOfModelMapStart(unittest.TestCase):
    """RestV10BimPlansGet200ResponseInnerAllOfModelMapStart unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10BimPlansGet200ResponseInnerAllOfModelMapStart:
        """Test RestV10BimPlansGet200ResponseInnerAllOfModelMapStart
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10BimPlansGet200ResponseInnerAllOfModelMapStart`
        """
        model = RestV10BimPlansGet200ResponseInnerAllOfModelMapStart()
        if include_optional:
            return RestV10BimPlansGet200ResponseInnerAllOfModelMapStart(
                x = 6.24,
                y = 12.48,
                z = 24.96
            )
        else:
            return RestV10BimPlansGet200ResponseInnerAllOfModelMapStart(
        )
        """

    def testRestV10BimPlansGet200ResponseInnerAllOfModelMapStart(self):
        """Test RestV10BimPlansGet200ResponseInnerAllOfModelMapStart"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
