# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body144_base_bid_inner_sub_sections_inner import Body144BaseBidInnerSubSectionsInner

class TestBody144BaseBidInnerSubSectionsInner(unittest.TestCase):
    """Body144BaseBidInnerSubSectionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body144BaseBidInnerSubSectionsInner:
        """Test Body144BaseBidInnerSubSectionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body144BaseBidInnerSubSectionsInner`
        """
        model = Body144BaseBidInnerSubSectionsInner()
        if include_optional:
            return Body144BaseBidInnerSubSectionsInner(
                id = 1235,
                title = 'Floors 10-19',
                position = 1,
                bid_form_items = [
                    procore_sdk.models.body_143_base_bid_inner_bid_form_items_inner.Body_143_base_bid_inner_bid_form_items_inner(
                        cost_code_id = 1, 
                        description = 'Concrete', 
                        position = 1, 
                        subject = 'Is the insurance of tools included in the Bid?', 
                        item_type = 'cost_code', 
                        response_type = 'amount', )
                    ]
            )
        else:
            return Body144BaseBidInnerSubSectionsInner(
        )
        """

    def testBody144BaseBidInnerSubSectionsInner(self):
        """Test Body144BaseBidInnerSubSectionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
