# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body32 import Body32

class TestBody32(unittest.TestCase):
    """Body32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body32:
        """Test Body32
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body32`
        """
        model = Body32()
        if include_optional:
            return Body32(
                logo = procore_sdk.models.body_32_logo.Body_32_logo(
                    upload_uuid = '1QJ83Q56CVQR4X3C0JG7YV86F8', 
                    file_name = 'my_file.png', )
            )
        else:
            return Body32(
        )
        """

    def testBody32(self):
        """Test Body32"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
