# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_work_breakdown_structure_wbs_codes_update_all_patch_request_attributes import RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes

class TestRestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes(unittest.TestCase):
    """RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes:
        """Test RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes`
        """
        model = RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes()
        if include_optional:
            return RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes(
                status = 'inactive'
            )
        else:
            return RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes(
        )
        """

    def testRestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes(self):
        """Test RestV10ProjectsProjectIdWorkBreakdownStructureWbsCodesUpdateAllPatchRequestAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
