# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rfq2 import RFQ2

class TestRFQ2(unittest.TestCase):
    """RFQ2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RFQ2:
        """Test RFQ2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RFQ2`
        """
        model = RFQ2()
        if include_optional:
            return RFQ2(
                id = 1199,
                commitment_contract_id = 418232,
                created_at = '2016-06-30T20:41:58Z',
                description = 'Please see attached documentation for Bulletin 3 and provide pricing within 1 week. If you don't get back to me, I'll assume you have no cost impact.',
                due_date = 'Thu Oct 13 00:00:00 UTC 2016',
                estimated_amount = 4302.0,
                estimated_schedule_impact = 2,
                estimated_status = 'rom',
                intent_to_quote = False,
                number = '013',
                original_quote = 4500.0,
                position = 13,
                private = True,
                prostore_file_ids = [3423484,6983730,2736492],
                status = 'under_review',
                title = 'Field Bulletin #3 - Steel staircase on roof',
                updated_at = '2016-08-30T18:11:43Z',
                specification_section = procore_sdk.models.rfq_specification_section.RFQ_specification_section(
                    specification_section_id = 32379, 
                    spec_section_description = 'Steel Structure', 
                    spec_section_number = '236400', ),
                created_by = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                    id = 160586, 
                    login = 'carl.contractor@example.com', 
                    name = 'Carl Contractor', ),
                assigned = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                    id = 160586, 
                    login = 'carl.contractor@example.com', 
                    name = 'Carl Contractor', ),
                location = procore_sdk.models.location.Location(
                    id = 15504, 
                    name = '1space>1 space', 
                    node_name = '1 space', 
                    parent_id = 788866, 
                    created_at = '2016-08-01T23:33:54Z', 
                    updated_at = '2016-08-01T23:33:54Z', ),
                cost_code = None
            )
        else:
            return RFQ2(
        )
        """

    def testRFQ2(self):
        """Test RFQ2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
