# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.quality_safety_punch_list_punch_item_assignments_api import QualitySafetyPunchListPunchItemAssignmentsApi


class TestQualitySafetyPunchListPunchItemAssignmentsApi(unittest.TestCase):
    """QualitySafetyPunchListPunchItemAssignmentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QualitySafetyPunchListPunchItemAssignmentsApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_projects_project_id_punch_item_assignments_id_get(self) -> None:
        """Test case for rest_v10_projects_project_id_punch_item_assignments_id_get

        Show Punch Assignment
        """
        pass

    def test_rest_v10_projects_project_id_punch_item_assignments_id_patch(self) -> None:
        """Test case for rest_v10_projects_project_id_punch_item_assignments_id_patch

        Update Punch Item Assignment
        """
        pass


if __name__ == '__main__':
    unittest.main()
