# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.core_project_project_roles_api import CoreProjectProjectRolesApi


class TestCoreProjectProjectRolesApi(unittest.TestCase):
    """CoreProjectProjectRolesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CoreProjectProjectRolesApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_project_roles_get(self) -> None:
        """Test case for rest_v10_project_roles_get

        List Project Roles
        """
        pass

    def test_rest_v10_project_roles_id_delete(self) -> None:
        """Test case for rest_v10_project_roles_id_delete

        Delete Project Role
        """
        pass

    def test_rest_v10_project_roles_post(self) -> None:
        """Test case for rest_v10_project_roles_post

        Create Project Role
        """
        pass


if __name__ == '__main__':
    unittest.main()
