# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_webhooks_hooks_post_request import RestV10WebhooksHooksPostRequest

class TestRestV10WebhooksHooksPostRequest(unittest.TestCase):
    """RestV10WebhooksHooksPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10WebhooksHooksPostRequest:
        """Test RestV10WebhooksHooksPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10WebhooksHooksPostRequest`
        """
        model = RestV10WebhooksHooksPostRequest()
        if include_optional:
            return RestV10WebhooksHooksPostRequest(
                company_id = 5358233,
                hook = procore_sdk.models.company_webhook_hook.company_webhook_hook(
                    api_version = 'v2', 
                    namespace = 'procore', 
                    destination_url = 'http://webhooks.mydomain.com', 
                    destination_headers = procore_sdk.models.company_webhook_hook_destination_headers.company_webhook_hook_destination_headers(
                        authorization = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9', ), ),
                project_id = 23498237
            )
        else:
            return RestV10WebhooksHooksPostRequest(
                company_id = 5358233,
                hook = procore_sdk.models.company_webhook_hook.company_webhook_hook(
                    api_version = 'v2', 
                    namespace = 'procore', 
                    destination_url = 'http://webhooks.mydomain.com', 
                    destination_headers = procore_sdk.models.company_webhook_hook_destination_headers.company_webhook_hook_destination_headers(
                        authorization = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzUxMiJ9', ), ),
                project_id = 23498237,
        )
        """

    def testRestV10WebhooksHooksPostRequest(self):
        """Test RestV10WebhooksHooksPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
