# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_file_versions_post_request_file_version import RestV10FileVersionsPostRequestFileVersion

class TestRestV10FileVersionsPostRequestFileVersion(unittest.TestCase):
    """RestV10FileVersionsPostRequestFileVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10FileVersionsPostRequestFileVersion:
        """Test RestV10FileVersionsPostRequestFileVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10FileVersionsPostRequestFileVersion`
        """
        model = RestV10FileVersionsPostRequestFileVersion()
        if include_optional:
            return RestV10FileVersionsPostRequestFileVersion(
                name = 'my.pdf',
                notes = 'This file version is good',
                data = '',
                upload_uuid = '1QJ83Q56CVQR4X3C0JG7YV86F8'
            )
        else:
            return RestV10FileVersionsPostRequestFileVersion(
                data = '',
        )
        """

    def testRestV10FileVersionsPostRequestFileVersion(self):
        """Test RestV10FileVersionsPostRequestFileVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
