# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_change_order_packages_post_request import RestV10ChangeOrderPackagesPostRequest

class TestRestV10ChangeOrderPackagesPostRequest(unittest.TestCase):
    """RestV10ChangeOrderPackagesPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ChangeOrderPackagesPostRequest:
        """Test RestV10ChangeOrderPackagesPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ChangeOrderPackagesPostRequest`
        """
        model = RestV10ChangeOrderPackagesPostRequest()
        if include_optional:
            return RestV10ChangeOrderPackagesPostRequest(
                project_id = 345357,
                contract_id = 64545,
                change_order = procore_sdk.models.rest_v10_change_order_packages_post_request_change_order.RestV10ChangeOrderPackagesPost_request_change_order(
                    status = 'draft', 
                    title = 'Additional Time & Materials', 
                    description = 'Additional Time & Materials for October', 
                    grand_total = '23474.0', 
                    schedule_impact_amount = 5, 
                    origin_code = 'ABC-123', 
                    origin_data = 'OD-123654789', 
                    origin_id = '654987123', 
                    paid_date = 'Sat Oct 22 00:00:00 UTC 2016', 
                    invoiced_date = 'Wed Oct 26 00:00:00 UTC 2016', 
                    due_date = 'Sun Oct 23 00:00:00 UTC 2016', 
                    executed = True, 
                    signed_change_order_received_date = 'Sun Oct 23 00:00:00 UTC 2016', )
            )
        else:
            return RestV10ChangeOrderPackagesPostRequest(
                project_id = 345357,
                contract_id = 64545,
                change_order = procore_sdk.models.rest_v10_change_order_packages_post_request_change_order.RestV10ChangeOrderPackagesPost_request_change_order(
                    status = 'draft', 
                    title = 'Additional Time & Materials', 
                    description = 'Additional Time & Materials for October', 
                    grand_total = '23474.0', 
                    schedule_impact_amount = 5, 
                    origin_code = 'ABC-123', 
                    origin_data = 'OD-123654789', 
                    origin_id = '654987123', 
                    paid_date = 'Sat Oct 22 00:00:00 UTC 2016', 
                    invoiced_date = 'Wed Oct 26 00:00:00 UTC 2016', 
                    due_date = 'Sun Oct 23 00:00:00 UTC 2016', 
                    executed = True, 
                    signed_change_order_received_date = 'Sun Oct 23 00:00:00 UTC 2016', ),
        )
        """

    def testRestV10ChangeOrderPackagesPostRequest(self):
        """Test RestV10ChangeOrderPackagesPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
