# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rfq4 import RFQ4

class TestRFQ4(unittest.TestCase):
    """RFQ4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RFQ4:
        """Test RFQ4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RFQ4`
        """
        model = RFQ4()
        if include_optional:
            return RFQ4(
                id = 1199,
                commitment_contract_id = 418232,
                created_at = '2016-06-30T20:41:58Z',
                deleted_at = '2016-08-30T18:11:43Z',
                description = 'Please see attached documentation for Bulletin 3 and provide pricing within 1 week. If you don't get back to me, I'll assume you have no cost impact.',
                due_date = 'Thu Oct 13 00:00:00 UTC 2016',
                estimated_amount = 4302.0,
                estimated_schedule_impact = 2,
                estimated_status = 'rom',
                intent_to_quote = False,
                number = '013',
                original_quote = 4500.0,
                position = 13,
                private = True,
                prostore_file_ids = [3423484,6983730,2736492],
                status = 'under_review',
                title = 'Field Bulletin #3 - Steel staircase on roof',
                updated_at = '2016-08-30T18:11:43Z',
                specification_section = procore_sdk.models.rfq_specification_section.RFQ_specification_section(
                    specification_section_id = 32379, 
                    spec_section_description = 'Steel Structure', 
                    spec_section_number = '236400', ),
                quotes = [
                    procore_sdk.models.rfq_quote.RFQ Quote(
                        id = 105445, 
                        commitment_quote_number = '2234', 
                        cost = 4500.0, 
                        schedule_impact = 2, 
                        description = 'Need to destroy some of the roofing to install this staircase.', 
                        request_for_quote_id = 136264, 
                        attachments_count = 1, 
                        import_origin_id = 'QWA44H', 
                        created_by_id = 5136213, 
                        created_at = '2016-10-21T21:39:41Z', 
                        deleted_at = '2016-10-23T21:44:45Z', 
                        updated_at = '2016-10-22T21:41:42Z', 
                        prostore_file_ids = [2334,776843,22456], 
                        created_by = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                            id = 160586, 
                            login = 'carl.contractor@example.com', 
                            name = 'Carl Contractor', ), )
                    ],
                responses = [
                    procore_sdk.models.rfq_response.RFQ Response(
                        id = 105, 
                        comment = 'This quote needs to be revised. See attached files.', 
                        created_at = '2016-10-22T21:39:40Z', 
                        deleted_at = '2016-10-30T21:39:40Z', 
                        updated_at = '2016-10-26T21:39:40Z', 
                        prostore_file_ids = [3453247,6543893,3476145], 
                        created_by = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                            id = 160586, 
                            login = 'carl.contractor@example.com', 
                            name = 'Carl Contractor', ), )
                    ],
                potential_change_orders = procore_sdk.models.rfq_potential_change_orders.RFQ_potential_change_orders(
                    id = 570623, 
                    created_at = '2012-10-23T21:39:40Z', 
                    created_by_id = 12, 
                    deleted_at = '2012-11-24T21:39:40Z', 
                    due_date = 'Fri Nov 23 00:00:00 UTC 2012', 
                    invoiced_date = 'Wed Oct 24 00:00:00 UTC 2012', 
                    number = '004', 
                    paid_date = 'Wed Nov 21 00:00:00 UTC 2012', 
                    reviewed_at = '2012-10-23T21:44:40Z', 
                    title = 'Field Bulletin #3 - Steel staircase on roof', 
                    status = 'approved', 
                    updated_at = '2012-11-23T21:39:40Z', 
                    change_order_request_id = 283764, 
                    executed = False, 
                    grand_total = '3329738.0', 
                    revision = 4, 
                    schedule_impact_amount = 2, 
                    change_reason = 'Deleted', 
                    change_order_request_title = 'Concrete freezer slab', 
                    change_order_package_title = 'Concrete freezer slab', 
                    potential_change_order_acronym_number = 'PCO 95', 
                    change_order_request_acronym_number = 'COR 9001', 
                    change_order_package_acronym_number = 'CCO 42', 
                    change_order_tiers = 3, ),
                change_order_packages = procore_sdk.models.rfq_change_order_packages.RFQ_change_order_packages(
                    id = 458661, 
                    contract_id = 64545, 
                    created_at = '2012-10-23T21:39:40Z', 
                    deleted_at = '2017-07-29T21:39:40Z', 
                    due_date = 'Fri Nov 23 00:00:00 UTC 2012', 
                    invoiced_date = 'Wed Oct 24 00:00:00 UTC 2012', 
                    number = '002', 
                    origin_data = 'OD-123654789', 
                    origin_id = '654987123', 
                    paid_date = 'Wed Nov 21 00:00:00 UTC 2012', 
                    reviewed_at = '2012-11-23T21:39:40Z', 
                    title = 'November Changes', 
                    status = 'approved', 
                    updated_at = '2012-11-23T21:39:40Z', ),
                commitment_potential_change_orders = procore_sdk.models.rfq_potential_change_orders.RFQ_potential_change_orders(
                    id = 570623, 
                    created_at = '2012-10-23T21:39:40Z', 
                    created_by_id = 12, 
                    deleted_at = '2012-11-24T21:39:40Z', 
                    due_date = 'Fri Nov 23 00:00:00 UTC 2012', 
                    invoiced_date = 'Wed Oct 24 00:00:00 UTC 2012', 
                    number = '004', 
                    paid_date = 'Wed Nov 21 00:00:00 UTC 2012', 
                    reviewed_at = '2012-10-23T21:44:40Z', 
                    title = 'Field Bulletin #3 - Steel staircase on roof', 
                    status = 'approved', 
                    updated_at = '2012-11-23T21:39:40Z', 
                    change_order_request_id = 283764, 
                    executed = False, 
                    grand_total = '3329738.0', 
                    revision = 4, 
                    schedule_impact_amount = 2, 
                    change_reason = 'Deleted', 
                    change_order_request_title = 'Concrete freezer slab', 
                    change_order_package_title = 'Concrete freezer slab', 
                    potential_change_order_acronym_number = 'PCO 95', 
                    change_order_request_acronym_number = 'COR 9001', 
                    change_order_package_acronym_number = 'CCO 42', 
                    change_order_tiers = 3, ),
                commitment_change_order_packages = procore_sdk.models.rfq_change_order_packages.RFQ_change_order_packages(
                    id = 458661, 
                    contract_id = 64545, 
                    created_at = '2012-10-23T21:39:40Z', 
                    deleted_at = '2017-07-29T21:39:40Z', 
                    due_date = 'Fri Nov 23 00:00:00 UTC 2012', 
                    invoiced_date = 'Wed Oct 24 00:00:00 UTC 2012', 
                    number = '002', 
                    origin_data = 'OD-123654789', 
                    origin_id = '654987123', 
                    paid_date = 'Wed Nov 21 00:00:00 UTC 2012', 
                    reviewed_at = '2012-11-23T21:39:40Z', 
                    title = 'November Changes', 
                    status = 'approved', 
                    updated_at = '2012-11-23T21:39:40Z', ),
                created_by = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                    id = 160586, 
                    login = 'carl.contractor@example.com', 
                    name = 'Carl Contractor', ),
                assigned = procore_sdk.models.rest_v10_projects_project_id_work_logs_get_200_response_inner_created_by.RestV10ProjectsProjectIdWorkLogsGet_200_response_inner_created_by(
                    id = 160586, 
                    login = 'carl.contractor@example.com', 
                    name = 'Carl Contractor', ),
                location = procore_sdk.models.location.Location(
                    id = 15504, 
                    name = '1space>1 space', 
                    node_name = '1 space', 
                    parent_id = 788866, 
                    created_at = '2016-08-01T23:33:54Z', 
                    updated_at = '2016-08-01T23:33:54Z', ),
                cost_code = None
            )
        else:
            return RFQ4(
        )
        """

    def testRFQ4(self):
        """Test RFQ4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
