# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_coordination_issues_filter_options_get200_response_inner import RestV10CoordinationIssuesFilterOptionsGet200ResponseInner

class TestRestV10CoordinationIssuesFilterOptionsGet200ResponseInner(unittest.TestCase):
    """RestV10CoordinationIssuesFilterOptionsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CoordinationIssuesFilterOptionsGet200ResponseInner:
        """Test RestV10CoordinationIssuesFilterOptionsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CoordinationIssuesFilterOptionsGet200ResponseInner`
        """
        model = RestV10CoordinationIssuesFilterOptionsGet200ResponseInner()
        if include_optional:
            return RestV10CoordinationIssuesFilterOptionsGet200ResponseInner(
                key = 'status',
                value = 'Status',
                endpoint = '/rest/v1.0/coordination_issues/filter_options/status?project_id=1'
            )
        else:
            return RestV10CoordinationIssuesFilterOptionsGet200ResponseInner(
        )
        """

    def testRestV10CoordinationIssuesFilterOptionsGet200ResponseInner(self):
        """Test RestV10CoordinationIssuesFilterOptionsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
