# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.time_and_material_timecard_body import TimeAndMaterialTimecardBody

class TestTimeAndMaterialTimecardBody(unittest.TestCase):
    """TimeAndMaterialTimecardBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeAndMaterialTimecardBody:
        """Test TimeAndMaterialTimecardBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeAndMaterialTimecardBody`
        """
        model = TimeAndMaterialTimecardBody()
        if include_optional:
            return TimeAndMaterialTimecardBody(
                time_and_material_timecard = procore_sdk.models.time_and_material_timecard_properties.Time and Material Timecard Properties(
                    time_and_material_entry_id = 13, 
                    timecard_time_type_id = 13, 
                    login_information_id = 10, 
                    work_classification_id = 10, 
                    hours_worked = 7.5, )
            )
        else:
            return TimeAndMaterialTimecardBody(
                time_and_material_timecard = procore_sdk.models.time_and_material_timecard_properties.Time and Material Timecard Properties(
                    time_and_material_entry_id = 13, 
                    timecard_time_type_id = 13, 
                    login_information_id = 10, 
                    work_classification_id = 10, 
                    hours_worked = 7.5, ),
        )
        """

    def testTimeAndMaterialTimecardBody(self):
        """Test TimeAndMaterialTimecardBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
