# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.field_productivity_time_and_materials_time_and_material_attachment_api import FieldProductivityTimeAndMaterialsTimeAndMaterialAttachmentApi


class TestFieldProductivityTimeAndMaterialsTimeAndMaterialAttachmentApi(unittest.TestCase):
    """FieldProductivityTimeAndMaterialsTimeAndMaterialAttachmentApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FieldProductivityTimeAndMaterialsTimeAndMaterialAttachmentApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_projects_project_id_time_and_material_entry_attachments_bulk_destroy_delete(self) -> None:
        """Test case for rest_v10_projects_project_id_time_and_material_entry_attachments_bulk_destroy_delete

        Bulk Delete Time and Material Attachments
        """
        pass

    def test_rest_v10_projects_project_id_time_and_material_entry_attachments_get(self) -> None:
        """Test case for rest_v10_projects_project_id_time_and_material_entry_attachments_get

        List all attachments
        """
        pass

    def test_rest_v10_projects_project_id_time_and_material_entry_attachments_id_delete(self) -> None:
        """Test case for rest_v10_projects_project_id_time_and_material_entry_attachments_id_delete

        Delete a Time and Material Attachment
        """
        pass

    def test_rest_v10_projects_project_id_time_and_material_entry_attachments_id_get(self) -> None:
        """Test case for rest_v10_projects_project_id_time_and_material_entry_attachments_id_get

        Show an individual time and material attachment
        """
        pass

    def test_rest_v10_projects_project_id_time_and_material_entry_attachments_post(self) -> None:
        """Test case for rest_v10_projects_project_id_time_and_material_entry_attachments_post

        Create attachment
        """
        pass


if __name__ == '__main__':
    unittest.main()
