# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.severity_level import SeverityLevel

class TestSeverityLevel(unittest.TestCase):
    """SeverityLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeverityLevel:
        """Test SeverityLevel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeverityLevel`
        """
        model = SeverityLevel()
        if include_optional:
            return SeverityLevel(
                id = 1,
                name = 'major',
                procore_default_name = 'major',
                active = False,
                email_trigger = False,
                push_notification_trigger = False,
                order = 56,
                created_at = '2016-10-25T17:53:35Z',
                updated_at = '2016-10-25T17:53:35Z'
            )
        else:
            return SeverityLevel(
        )
        """

    def testSeverityLevel(self):
        """Test SeverityLevel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
