# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_recycle_bin_action_plans_plan_sections_get200_response_inner import RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner

class TestRestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner(unittest.TestCase):
    """RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner:
        """Test RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner`
        """
        model = RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner()
        if include_optional:
            return RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner(
                id = 43584,
                created_at = '2018-09-20T21:39:40Z',
                deleted_at = '2017-01-16T18:42:12Z',
                plan_id = 57,
                position = 3,
                title = 'A New Action Plan Section',
                updated_at = '2018-09-20T21:39:40Z'
            )
        else:
            return RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner(
        )
        """

    def testRestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner(self):
        """Test RestV10ProjectsProjectIdRecycleBinActionPlansPlanSectionsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
