# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_budget_line_items_post201_response import RestV10BudgetLineItemsPost201Response

class TestRestV10BudgetLineItemsPost201Response(unittest.TestCase):
    """RestV10BudgetLineItemsPost201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10BudgetLineItemsPost201Response:
        """Test RestV10BudgetLineItemsPost201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10BudgetLineItemsPost201Response`
        """
        model = RestV10BudgetLineItemsPost201Response()
        if include_optional:
            return RestV10BudgetLineItemsPost201Response(
                id = 75414,
                original_budget_amount = 20000.0,
                uom = 'hours',
                quantity = 250.5,
                unit_cost = 123.5,
                calculation_strategy = 'manual',
                approved_budget_changes = 0.0,
                revised_budget = 20000.0,
                pending_budget_changes = 0.0,
                projected_budget = 20000.0,
                committed_costs = 0.0,
                direct_costs = 0.0,
                pending_cost_changes = 0.0,
                projected_costs = 0.0,
                budget_forecast = 20000.0,
                estimated_cost_at_completion = 20000.0,
                projected_over_under = 0.0,
                cost_code = procore_sdk.models.rest_v10_budget_line_items_post_201_response_cost_code.RestV10BudgetLineItemsPost_201_response_cost_code(
                    id = 32780682, 
                    name = 'Wood Sub-floors', 
                    code = '162', 
                    full_code = '17-162', ),
                division = procore_sdk.models.rest_v10_budget_line_items_post_201_response_division.RestV10BudgetLineItemsPost_201_response_division(
                    id = 236246, 
                    name = 'Wood floors', 
                    full_code = '11-123', ),
                line_item_type = procore_sdk.models.rest_v10_budget_line_items_post_201_response_line_item_type.RestV10BudgetLineItemsPost_201_response_line_item_type(
                    id = 23107, 
                    name = 'Equipment', ),
                currency_configuration = procore_sdk.models.rest_v11_budget_line_items_post_201_response_currency_configuration.RestV11BudgetLineItemsPost_201_response_currency_configuration(
                    currency_iso_code = 'USD', )
            )
        else:
            return RestV10BudgetLineItemsPost201Response(
        )
        """

    def testRestV10BudgetLineItemsPost201Response(self):
        """Test RestV10BudgetLineItemsPost201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
