# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.project_management_bidding_bid_forms_api import ProjectManagementBiddingBidFormsApi


class TestProjectManagementBiddingBidFormsApi(unittest.TestCase):
    """ProjectManagementBiddingBidFormsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectManagementBiddingBidFormsApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_bid_leveling_get(self) -> None:
        """Test case for rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_bid_leveling_get

        Bid Level across a Bid Form
        """
        pass

    def test_rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_delete(self) -> None:
        """Test case for rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_delete

        Delete Bid Form
        """
        pass

    def test_rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_get(self) -> None:
        """Test case for rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_get

        View Bid Form
        """
        pass

    def test_rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_patch(self) -> None:
        """Test case for rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_patch

        Update Bid Form
        """
        pass

    def test_rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_get(self) -> None:
        """Test case for rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_get

        Index Bid Forms
        """
        pass

    def test_rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_post(self) -> None:
        """Test case for rest_v10_projects_project_id_bid_packages_bid_package_id_bid_forms_post

        Create a Bid Form
        """
        pass

    def test_rest_v11_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_bid_leveling_get(self) -> None:
        """Test case for rest_v11_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_bid_leveling_get

        Bid Level across a Bid Form
        """
        pass

    def test_rest_v11_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_patch(self) -> None:
        """Test case for rest_v11_projects_project_id_bid_packages_bid_package_id_bid_forms_bid_form_id_patch

        Update Bid Form
        """
        pass

    def test_rest_v11_projects_project_id_bid_packages_bid_package_id_bid_forms_post(self) -> None:
        """Test case for rest_v11_projects_project_id_bid_packages_bid_package_id_bid_forms_post

        Create a Bid Form
        """
        pass


if __name__ == '__main__':
    unittest.main()
