# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.cost_code1 import CostCode1

class TestCostCode1(unittest.TestCase):
    """CostCode1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CostCode1:
        """Test CostCode1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CostCode1`
        """
        model = CostCode1()
        if include_optional:
            return CostCode1(
                position = 1,
                code = '300',
                name = 'Site Work',
                origin_data = 'OD-239238',
                origin_id = '3497237',
                parent_id = 12345,
                standard_cost_code_id = 122334
            )
        else:
            return CostCode1(
                code = '300',
                name = 'Site Work',
        )
        """

    def testCostCode1(self):
        """Test CostCode1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
