# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_change_events_get200_response_inner_change_event_line_items_inner_budget_code import RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode

class TestRestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode(unittest.TestCase):
    """RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode:
        """Test RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode`
        """
        model = RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode()
        if include_optional:
            return RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode(
                id = 1,
                flat_code = 'O.01-511',
                description = 'Earthwork.Materials',
                segment_items = [
                    procore_sdk.models.rest_v10_companies_company_id_work_breakdown_structure_segments_segment_id_segment_items_get_200_response_inner.RestV10CompaniesCompanyIdWorkBreakdownStructureSegmentsSegmentIdSegmentItemsGet_200_response_inner(
                        id = 456, 
                        code = '01-222', 
                        name = 'Lighting', 
                        created_at = '2016-06-30T20:41:58Z', 
                        updated_at = '2016-08-30T18:11:43Z', 
                        parent_id = 123, 
                        path_ids = [123,456], 
                        path_code = 'a', 
                        is_parent = False, 
                        path_codes = ["01 - Requirements","01-222 - Lighting"], 
                        path_names = ["01 - Requirements","01-222 - Lighting"], 
                        in_use = True, 
                        segment = {"id":3,"name":"Cost Code","type":"cost_code","position":1,"delimiter":".","required":true,"segment_items_count":2,"project_can_modify_origin_project":true,"project_can_delete_origin_company":true,"structure":"tiered","created_at":"2016-06-30T20:41:58Z","updated_at":"2016-08-30T18:11:43Z","wbs_pattern_id":4567}, 
                        status = 'active', )
                    ]
            )
        else:
            return RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode(
        )
        """

    def testRestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode(self):
        """Test RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetCode"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
