# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_companies_company_id_settings_logo_put200_response_inner import RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner

class TestRestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner(unittest.TestCase):
    """RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner:
        """Test RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner`
        """
        model = RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner()
        if include_optional:
            return RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner(
                name = 'welcome_tour_dismissed',
                value = 'GST@10%',
                is_user_flag = True
            )
        else:
            return RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner(
        )
        """

    def testRestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner(self):
        """Test RestV10CompaniesCompanyIdSettingsLogoPut200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
