# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.checklist_item_response import ChecklistItemResponse

class TestChecklistItemResponse(unittest.TestCase):
    """ChecklistItemResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChecklistItemResponse:
        """Test ChecklistItemResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChecklistItemResponse`
        """
        model = ChecklistItemResponse()
        if include_optional:
            return ChecklistItemResponse(
                item_id = 4323,
                status = 'conforming',
                responded_at = '2018-10-23T21:39:40Z',
                responder = procore_sdk.models.rest_v10_projects_project_id_checklist_list_templates_post_201_response_all_of_created_by.RestV10ProjectsProjectIdChecklistListTemplatesPost_201_response_allOf_created_by(
                    id = 160586, 
                    login = 'exampleuser@example.com', 
                    name = 'Carl Contractor', ),
                item_type = procore_sdk.models.checklist_item_type.ChecklistItemType(
                    id = 1, 
                    category = 'multiple_choice', 
                    name = 'default', ),
                payload = procore_sdk.models.checklist_item_response_payload.ChecklistItemResponse_payload(
                    text_value = 'Supplies arrived at 10:00 AM', 
                    number_value = 4232, 
                    date_value = 'Sun Jan 20 00:00:00 UTC 2019', 
                    response_option = procore_sdk.models.checklist_item_response_payload_response_option.ChecklistItemResponse_payload_response_option(
                        id = 3432, 
                        name = 'Safe', ), )
            )
        else:
            return ChecklistItemResponse(
        )
        """

    def testChecklistItemResponse(self):
        """Test ChecklistItemResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
