# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_webhooks_hooks_hook_id_triggers_bulk_post200_response import RestV10WebhooksHooksHookIdTriggersBulkPost200Response

class TestRestV10WebhooksHooksHookIdTriggersBulkPost200Response(unittest.TestCase):
    """RestV10WebhooksHooksHookIdTriggersBulkPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10WebhooksHooksHookIdTriggersBulkPost200Response:
        """Test RestV10WebhooksHooksHookIdTriggersBulkPost200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10WebhooksHooksHookIdTriggersBulkPost200Response`
        """
        model = RestV10WebhooksHooksHookIdTriggersBulkPost200Response()
        if include_optional:
            return RestV10WebhooksHooksHookIdTriggersBulkPost200Response(
                success = [
                    procore_sdk.models.webhooks_trigger.Webhooks Trigger(
                        id = 231346546, 
                        webhook_hook_id = 43593499, 
                        resource_name = 'Project Users', 
                        resource_id = 43597433, 
                        event_type = 'DELETE', 
                        company_id = 5358233, 
                        project_id = 23498237, 
                        user_id = 532323, )
                    ]
            )
        else:
            return RestV10WebhooksHooksHookIdTriggersBulkPost200Response(
        )
        """

    def testRestV10WebhooksHooksHookIdTriggersBulkPost200Response(self):
        """Test RestV10WebhooksHooksHookIdTriggersBulkPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
