# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body22_files_inner import Body22FilesInner

class TestBody22FilesInner(unittest.TestCase):
    """Body22FilesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body22FilesInner:
        """Test Body22FilesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body22FilesInner`
        """
        model = Body22FilesInner()
        if include_optional:
            return Body22FilesInner(
                type = 'prostore_file',
                id = 1234,
                url = 'https://example.com/foo.pdf'
            )
        else:
            return Body22FilesInner(
                type = 'prostore_file',
                id = 1234,
        )
        """

    def testBody22FilesInner(self):
        """Test Body22FilesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
