# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_change_events_get200_response_inner_change_event_line_items_inner_budget_mod import RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod

class TestRestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod(unittest.TestCase):
    """RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod:
        """Test RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod`
        """
        model = RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod()
        if include_optional:
            return RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod(
                created_at = '2016-10-23T21:39:40Z',
                transfer_amount = '4500.0',
                notes = 'Transfer money for extra concrete.',
                from_budget_line_item_id = 348383,
                to_budget_line_item_id = 4034034,
                from_budget_line_item_name = 'Source Line Item',
                to_budget_line_item_name = 'Target Line Item'
            )
        else:
            return RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod(
        )
        """

    def testRestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod(self):
        """Test RestV10ChangeEventsGet200ResponseInnerChangeEventLineItemsInnerBudgetMod"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
