# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.folder2 import Folder2

class TestFolder2(unittest.TestCase):
    """Folder2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Folder2:
        """Test Folder2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Folder2`
        """
        model = Folder2()
        if include_optional:
            return Folder2(
                id = 2,
                name = 'Subfolder',
                name_with_path = 'Root Folder/Subfolder'
            )
        else:
            return Folder2(
        )
        """

    def testFolder2(self):
        """Test Folder2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
