# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.body13_updates_inner import Body13UpdatesInner

class TestBody13UpdatesInner(unittest.TestCase):
    """Body13UpdatesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Body13UpdatesInner:
        """Test Body13UpdatesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Body13UpdatesInner`
        """
        model = Body13UpdatesInner()
        if include_optional:
            return Body13UpdatesInner(
                id = 123,
                code = 'GST@10%',
                description = 'Goods and Services Tax',
                origin_data = '{ parent_ids: [1,2] }',
                origin_id = '1VT-33778-013',
                rate1 = 10,
                archived = False
            )
        else:
            return Body13UpdatesInner(
        )
        """

    def testBody13UpdatesInner(self):
        """Test Body13UpdatesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
