# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.budgeted_production_quantity_body import BudgetedProductionQuantityBody

class TestBudgetedProductionQuantityBody(unittest.TestCase):
    """BudgetedProductionQuantityBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BudgetedProductionQuantityBody:
        """Test BudgetedProductionQuantityBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BudgetedProductionQuantityBody`
        """
        model = BudgetedProductionQuantityBody()
        if include_optional:
            return BudgetedProductionQuantityBody(
                budgeted_production_quantity = procore_sdk.models.budgeted_production_quantity.BudgetedProductionQuantity(
                    project_id = 1, 
                    cost_code_id = 1, 
                    wbs_code_id = 56, 
                    quantity = 10.49, 
                    unit_of_measure = 'sf', )
            )
        else:
            return BudgetedProductionQuantityBody(
                budgeted_production_quantity = procore_sdk.models.budgeted_production_quantity.BudgetedProductionQuantity(
                    project_id = 1, 
                    cost_code_id = 1, 
                    wbs_code_id = 56, 
                    quantity = 10.49, 
                    unit_of_measure = 'sf', ),
        )
        """

    def testBudgetedProductionQuantityBody(self):
        """Test BudgetedProductionQuantityBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
