# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.api.quality_safety_incidents_harm_sources_api import QualitySafetyIncidentsHarmSourcesApi


class TestQualitySafetyIncidentsHarmSourcesApi(unittest.TestCase):
    """QualitySafetyIncidentsHarmSourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QualitySafetyIncidentsHarmSourcesApi()

    def tearDown(self) -> None:
        pass

    def test_rest_v10_companies_company_id_incidents_harm_sources_bulk_update_patch(self) -> None:
        """Test case for rest_v10_companies_company_id_incidents_harm_sources_bulk_update_patch

        Bulk Update Harm Sources
        """
        pass

    def test_rest_v10_companies_company_id_incidents_harm_sources_get(self) -> None:
        """Test case for rest_v10_companies_company_id_incidents_harm_sources_get

        List Harm Sources
        """
        pass

    def test_rest_v10_companies_company_id_incidents_harm_sources_id_delete(self) -> None:
        """Test case for rest_v10_companies_company_id_incidents_harm_sources_id_delete

        Delete Harm Source
        """
        pass

    def test_rest_v10_companies_company_id_incidents_harm_sources_id_get(self) -> None:
        """Test case for rest_v10_companies_company_id_incidents_harm_sources_id_get

        Show Harm Source
        """
        pass

    def test_rest_v10_companies_company_id_incidents_harm_sources_id_patch(self) -> None:
        """Test case for rest_v10_companies_company_id_incidents_harm_sources_id_patch

        Update Harm Source
        """
        pass

    def test_rest_v10_companies_company_id_incidents_harm_sources_post(self) -> None:
        """Test case for rest_v10_companies_company_id_incidents_harm_sources_post

        Create Harm Source
        """
        pass


if __name__ == '__main__':
    unittest.main()
