# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from procore_sdk.models.rest_v10_projects_project_id_action_plans_plan_templates_get200_response_inner import RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner

class TestRestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner(unittest.TestCase):
    """RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner:
        """Test RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner`
        """
        model = RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner()
        if include_optional:
            return RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner(
                id = 43584,
                created_at = '2018-09-20T21:39:40Z',
                description = '<p>Important Safety Project Action Plan Template.</p>',
                description_plain_text = 'Important Safety Project Action Plan Template.',
                location = procore_sdk.models.location.Location(
                    id = 15504, 
                    name = 'North Building>First Floor>Electrical Closet', 
                    node_name = 'Electrical Closet', 
                    parent_id = 788866, 
                    created_at = '2016-08-01T23:33:54Z', 
                    updated_at = '2016-08-01T23:33:54Z', 
                    code = 'L1', ),
                manager = procore_sdk.models.rest_v10_projects_project_id_action_plans_plan_templates_get_200_response_inner_manager.RestV10ProjectsProjectIdActionPlansPlanTemplatesGet_200_response_inner_manager(
                    id = 23, 
                    first_name = 'Paul', 
                    last_name = 'Admin', 
                    name = 'Paul Admin', 
                    user_id = 453, 
                    is_employee = True, 
                    employee_id = '12', 
                    login = 'login@example.com', 
                    updated_at = '2018-09-20T21:39:40Z', 
                    vendor = procore_sdk.models.rest_v10_projects_project_id_action_plans_plan_templates_get_200_response_inner_manager_vendor.RestV10ProjectsProjectIdActionPlansPlanTemplatesGet_200_response_inner_manager_vendor(
                        id = 223, 
                        name = 'Freddie's Excavating', ), ),
                status = 'draft',
                private = False,
                title = 'A New Project Action Plan Template',
                plan_type = procore_sdk.models.rest_v10_projects_project_id_action_plans_plan_templates_get_200_response_inner_plan_type.RestV10ProjectsProjectIdActionPlansPlanTemplatesGet_200_response_inner_plan_type(
                    id = 21, 
                    active = True, 
                    created_at = '2018-09-20T21:39:40Z', 
                    name = 'Safety', 
                    updated_at = '2018-09-20T21:39:40Z', 
                    source_key = 'safety', ),
                provider_type = 'project',
                updated_at = '2015-03-19T12:00Z'
            )
        else:
            return RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner(
        )
        """

    def testRestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner(self):
        """Test RestV10ProjectsProjectIdActionPlansPlanTemplatesGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
