# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from procore_sdk.models.rest_v10_projects_project_id_work_logs_get200_response_inner_created_by import RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy
from procore_sdk.models.rest_v10_work_order_contracts_work_order_contract_id_line_items_sync_patch200_response_errors_inner_all_of_errors import RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors
from typing import Optional, Set
from typing_extensions import Self

class ArrayOfChangeOrderRequestsErrorsInner(BaseModel):
    """
    ArrayOfChangeOrderRequestsErrorsInner
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="ID")
    change_order_package_id: Optional[StrictInt] = Field(default=None, description="Change Order Package ID")
    contract_id: Optional[StrictInt] = Field(default=None, description="Contract ID")
    created_at: Optional[datetime] = Field(default=None, description="Created at")
    creator: Optional[RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy] = None
    deleted_at: Optional[datetime] = Field(default=None, description="Deleted at")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    due_date: Optional[datetime] = Field(default=None, description="Due date")
    grand_total: Optional[StrictStr] = Field(default=None, description="Total including markup")
    invoiced_date: Optional[date] = Field(default=None, description="Invoiced date")
    number: Optional[StrictStr] = Field(default=None, description="Number")
    origin_data: Optional[StrictStr] = Field(default=None, description="Origin data")
    origin_id: Optional[StrictStr] = Field(default=None, description="Origin ID")
    paid_date: Optional[date] = Field(default=None, description="Paid date")
    position: Optional[StrictInt] = Field(default=None, description="Position")
    private: Optional[StrictBool] = Field(default=None, description="If true, visible to admins only; otherwise visible to those with access to the parent contract.")
    revision: Optional[StrictInt] = Field(default=None, description="Revision")
    schedule_impact_amount: Optional[StrictInt] = Field(default=None, description="Schedule impact in days")
    status: Optional[StrictStr] = Field(default=None, description="Status")
    title: Optional[StrictStr] = Field(default=None, description="Title")
    updated_at: Optional[datetime] = Field(default=None, description="Updated at")
    errors: Optional[RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors] = None
    __properties: ClassVar[List[str]] = ["id", "change_order_package_id", "contract_id", "created_at", "creator", "deleted_at", "description", "due_date", "grand_total", "invoiced_date", "number", "origin_data", "origin_id", "paid_date", "position", "private", "revision", "schedule_impact_amount", "status", "title", "updated_at", "errors"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['draft', 'not_pricing', 'pricing', 'pending', 'revised', 'proceeding', 'not_proceeding', 'no_charge', 'approved', 'rejected', 'void']):
            raise ValueError("must be one of enum values ('draft', 'not_pricing', 'pricing', 'pending', 'revised', 'proceeding', 'not_proceeding', 'no_charge', 'approved', 'rejected', 'void')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArrayOfChangeOrderRequestsErrorsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of creator
        if self.creator:
            _dict['creator'] = self.creator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of errors
        if self.errors:
            _dict['errors'] = self.errors.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArrayOfChangeOrderRequestsErrorsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "change_order_package_id": obj.get("change_order_package_id"),
            "contract_id": obj.get("contract_id"),
            "created_at": obj.get("created_at"),
            "creator": RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.from_dict(obj["creator"]) if obj.get("creator") is not None else None,
            "deleted_at": obj.get("deleted_at"),
            "description": obj.get("description"),
            "due_date": obj.get("due_date"),
            "grand_total": obj.get("grand_total"),
            "invoiced_date": obj.get("invoiced_date"),
            "number": obj.get("number"),
            "origin_data": obj.get("origin_data"),
            "origin_id": obj.get("origin_id"),
            "paid_date": obj.get("paid_date"),
            "position": obj.get("position"),
            "private": obj.get("private"),
            "revision": obj.get("revision"),
            "schedule_impact_amount": obj.get("schedule_impact_amount"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at"),
            "errors": RestV10WorkOrderContractsWorkOrderContractIdLineItemsSyncPatch200ResponseErrorsInnerAllOfErrors.from_dict(obj["errors"]) if obj.get("errors") is not None else None
        })
        return _obj


