# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from procore_sdk.models.bid_form_base_bid_section_bid_form_items_inner_bid_items_inner import BidFormBaseBidSectionBidFormItemsInnerBidItemsInner
from typing import Optional, Set
from typing_extensions import Self

class BidFormBaseBidSectionBidFormItemsInner(BaseModel):
    """
    A row of bid items for a cost code
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="Bid Form Item ID")
    cost_code_id: Optional[StrictInt] = Field(default=None, description="Cost code ID")
    full_code: Optional[StrictStr] = Field(default=None, description="The Cost code Name & Number in one string")
    name: Optional[StrictStr] = Field(default=None, description="Cost Code Name")
    description: Optional[StrictStr] = Field(default=None, description="Description")
    number: Optional[StrictStr] = Field(default=None, description="Cost Code Number")
    item_type: Optional[StrictStr] = Field(default=None, description="Line Item Type")
    subject: Optional[StrictStr] = Field(default=None, description="Plain text subject")
    response_type: Optional[StrictStr] = Field(default=None, description="Bid Form Items can have various response types. This property determines which one is used.")
    bid_items: Optional[List[BidFormBaseBidSectionBidFormItemsInnerBidItemsInner]] = None
    __properties: ClassVar[List[str]] = ["id", "cost_code_id", "full_code", "name", "description", "number", "item_type", "subject", "response_type", "bid_items"]

    @field_validator('response_type')
    def response_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['amount', 'unit', 'include_exclude']):
            raise ValueError("must be one of enum values ('amount', 'unit', 'include_exclude')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BidFormBaseBidSectionBidFormItemsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bid_items (list)
        _items = []
        if self.bid_items:
            for _item_bid_items in self.bid_items:
                if _item_bid_items:
                    _items.append(_item_bid_items.to_dict())
            _dict['bid_items'] = _items
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BidFormBaseBidSectionBidFormItemsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "cost_code_id": obj.get("cost_code_id"),
            "full_code": obj.get("full_code"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "number": obj.get("number"),
            "item_type": obj.get("item_type"),
            "subject": obj.get("subject"),
            "response_type": obj.get("response_type"),
            "bid_items": [BidFormBaseBidSectionBidFormItemsInnerBidItemsInner.from_dict(_item) for _item in obj["bid_items"]] if obj.get("bid_items") is not None else None
        })
        return _obj


