# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from procore_sdk.models.body144_base_bid_inner_bid_form_items_inner import Body144BaseBidInnerBidFormItemsInner
from procore_sdk.models.body144_base_bid_inner_sub_sections_inner import Body144BaseBidInnerSubSectionsInner
from typing import Optional, Set
from typing_extensions import Self

class Body144AlternatesInner(BaseModel):
    """
    Body144AlternatesInner
    """ # noqa: E501
    title: Optional[StrictStr] = Field(default=None, description="Alternate Bid Form Item Title")
    position: Optional[StrictInt] = Field(default=None, description="Position")
    header: Optional[StrictBool] = Field(default=None, description="Whether the item is a header or not")
    bid_form_items: Optional[List[Body144BaseBidInnerBidFormItemsInner]] = Field(default=None, description="Bid Form Items")
    sub_sections: Optional[List[Body144BaseBidInnerSubSectionsInner]] = Field(default=None, description="Sub Sections")
    __properties: ClassVar[List[str]] = ["title", "position", "header", "bid_form_items", "sub_sections"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Body144AlternatesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in bid_form_items (list)
        _items = []
        if self.bid_form_items:
            for _item_bid_form_items in self.bid_form_items:
                if _item_bid_form_items:
                    _items.append(_item_bid_form_items.to_dict())
            _dict['bid_form_items'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sub_sections (list)
        _items = []
        if self.sub_sections:
            for _item_sub_sections in self.sub_sections:
                if _item_sub_sections:
                    _items.append(_item_sub_sections.to_dict())
            _dict['sub_sections'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Body144AlternatesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "title": obj.get("title"),
            "position": obj.get("position"),
            "header": obj.get("header"),
            "bid_form_items": [Body144BaseBidInnerBidFormItemsInner.from_dict(_item) for _item in obj["bid_form_items"]] if obj.get("bid_form_items") is not None else None,
            "sub_sections": [Body144BaseBidInnerSubSectionsInner.from_dict(_item) for _item in obj["sub_sections"]] if obj.get("sub_sections") is not None else None
        })
        return _obj


