# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Project2(BaseModel):
    """
    Project2
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=True, description="The project active status.")
    address: Optional[StrictStr] = Field(default=None, description="The street address of the project.")
    city: Optional[StrictStr] = Field(default=None, description="The city where the project is located.")
    code: Optional[StrictStr] = Field(default=None, description="The project code.")
    country_code: Optional[StrictStr] = Field(default=None, description="The country code (ISO-3166 Alpha-2 format) where the project is located.")
    description: Optional[StrictStr] = Field(default=None, description="The project description.")
    start_date: Optional[date] = Field(default=None, description="The date that the contract for the project is signed. Note: This field replaces estimated_start_date and will mirror its value.")
    completion_date: Optional[date] = Field(default=None, description="The date that all parties agree the project meets or must meet “substantial completion”. Note: This field replaces estimated_completion_date and will mirror its value.")
    total_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The total amount of construction work performed, planned, or put in place during the project. Note: This field is a replacement of estimated_value and will mirror its value.")
    warranty_start_date: Optional[date] = Field(default=None, description="The project warranty start date.")
    warranty_end_date: Optional[date] = Field(default=None, description="The project warranty end date.")
    flag: Optional[StrictStr] = Field(default=None, description="The project flag.")
    image_id: Optional[StrictInt] = Field(default=None, description="The project image identifier.")
    name: StrictStr = Field(description="The project name.")
    office_id: Optional[StrictInt] = Field(default=None, description="The project office identifier.")
    phone: Optional[StrictStr] = Field(default=None, description="The project telephone number.")
    project_number: Optional[StrictStr] = Field(default=None, description="The project number.")
    public_notes: Optional[StrictStr] = Field(default=None, description="The public notes for the project.")
    project_stage_id: Optional[StrictInt] = Field(default=None, description="The project stage identifier.")
    square_feet: Optional[StrictInt] = Field(default=None, description="The total square footage of the project.")
    state_code: Optional[StrictStr] = Field(default=None, description="The state code (ISO-3166 Alpha-2 format) where the project is located.")
    time_zone: Optional[StrictStr] = Field(default=None, description="The timezone where the project is located.")
    zip: Optional[StrictStr] = Field(default=None, description="The project postal code.")
    parent_job_id: Optional[StrictInt] = Field(default=None, description="The project's parent job identifier.")
    program_id: Optional[StrictInt] = Field(default=None, description="The project program identifier.")
    project_bid_type_id: Optional[StrictInt] = Field(default=None, description="The project bid type identifier.")
    project_type_id: Optional[StrictInt] = Field(default=None, description="The project type identifier.")
    project_owner_type_id: Optional[StrictInt] = Field(default=None, description="The project owner type identifier.")
    project_region_id: Optional[StrictInt] = Field(default=None, description="The project region id of the project.")
    project_template_id: Optional[StrictInt] = Field(default=None, description="The project template identifier as designated by another project on this company. It must be a project that is a template defined by `template: true`.")
    origin_id: Optional[StrictStr] = Field(default=None, description="External third-party identifier for the project.")
    origin_data: Optional[StrictStr] = Field(default=None, description="External third-party data string associated with the project.")
    origin_code: Optional[StrictStr] = Field(default=None, description="External third-party code associated with the project.")
    override_start_date: Optional[date] = Field(default=None, description="This is the date that the project started and will be displayed on the portfolio page.")
    override_start_date_check: Optional[StrictBool] = Field(default=None, description="This is the property that enables the use of the override_start_date as the Actual Start Date.")
    override_end_date: Optional[date] = Field(default=None, description="This is the date that the project will be finished and will be displayed on the portfolio page.")
    override_end_date_check: Optional[StrictBool] = Field(default=None, description="This is the property that enables the use of the override_end_date as the Projected Finish Date.")
    department_ids: Optional[List[StrictInt]] = Field(default=None, description="The department ids the project is associated with. The array should represent all departments, so if the current value is `[1, 2, 3]` and want to remove department `2`, then send `[1, 3]`.")
    estimated_value: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The estimated value of the project. Note: This field is now deprecated and will mirror the value of total_value until it is no longer supported.")
    estimated_start_date: Optional[date] = Field(default=None, description="The estimated start date of the project. Note: This field is now deprecated and will mirror the value of start_date until it is no longer supported.")
    estimated_completion_date: Optional[date] = Field(default=None, description="The estimated completion date of the project. Note: This field is now deprecated and will mirror the value of completion_date until it is no longer supported.")
    store_number: Optional[StrictStr] = Field(default=None, description="The project store number.")
    accounting_project_number: Optional[StrictStr] = Field(default=None, description="The project accounting project number.")
    designated_market_area: Optional[StrictStr] = Field(default=None, description="The project designated market area.")
    erp_integrated: Optional[StrictBool] = Field(default=False, description="The project will be ERP integrated.")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Project latitude")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Project longitude")
    enable_copy_of_standard_cost_codes: Optional[StrictBool] = Field(default=False, description="This property enables the user to copy default standard cost codes during new project creation when it is set to true. However, this flag does not have any impact when using project template, and the company's configuration is set to copy project template cost codes.")
    __properties: ClassVar[List[str]] = ["active", "address", "city", "code", "country_code", "description", "start_date", "completion_date", "total_value", "warranty_start_date", "warranty_end_date", "flag", "image_id", "name", "office_id", "phone", "project_number", "public_notes", "project_stage_id", "square_feet", "state_code", "time_zone", "zip", "parent_job_id", "program_id", "project_bid_type_id", "project_type_id", "project_owner_type_id", "project_region_id", "project_template_id", "origin_id", "origin_data", "origin_code", "override_start_date", "override_start_date_check", "override_end_date", "override_end_date_check", "department_ids", "estimated_value", "estimated_start_date", "estimated_completion_date", "store_number", "accounting_project_number", "designated_market_area", "erp_integrated", "latitude", "longitude", "enable_copy_of_standard_cost_codes"]

    @field_validator('flag')
    def flag_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Red', 'Yellow', 'Green']):
            raise ValueError("must be one of enum values ('Red', 'Yellow', 'Green')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Project2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if origin_id (nullable) is None
        # and model_fields_set contains the field
        if self.origin_id is None and "origin_id" in self.model_fields_set:
            _dict['origin_id'] = None

        # set to None if origin_data (nullable) is None
        # and model_fields_set contains the field
        if self.origin_data is None and "origin_data" in self.model_fields_set:
            _dict['origin_data'] = None

        # set to None if origin_code (nullable) is None
        # and model_fields_set contains the field
        if self.origin_code is None and "origin_code" in self.model_fields_set:
            _dict['origin_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Project2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active") if obj.get("active") is not None else True,
            "address": obj.get("address"),
            "city": obj.get("city"),
            "code": obj.get("code"),
            "country_code": obj.get("country_code"),
            "description": obj.get("description"),
            "start_date": obj.get("start_date"),
            "completion_date": obj.get("completion_date"),
            "total_value": obj.get("total_value"),
            "warranty_start_date": obj.get("warranty_start_date"),
            "warranty_end_date": obj.get("warranty_end_date"),
            "flag": obj.get("flag"),
            "image_id": obj.get("image_id"),
            "name": obj.get("name"),
            "office_id": obj.get("office_id"),
            "phone": obj.get("phone"),
            "project_number": obj.get("project_number"),
            "public_notes": obj.get("public_notes"),
            "project_stage_id": obj.get("project_stage_id"),
            "square_feet": obj.get("square_feet"),
            "state_code": obj.get("state_code"),
            "time_zone": obj.get("time_zone"),
            "zip": obj.get("zip"),
            "parent_job_id": obj.get("parent_job_id"),
            "program_id": obj.get("program_id"),
            "project_bid_type_id": obj.get("project_bid_type_id"),
            "project_type_id": obj.get("project_type_id"),
            "project_owner_type_id": obj.get("project_owner_type_id"),
            "project_region_id": obj.get("project_region_id"),
            "project_template_id": obj.get("project_template_id"),
            "origin_id": obj.get("origin_id"),
            "origin_data": obj.get("origin_data"),
            "origin_code": obj.get("origin_code"),
            "override_start_date": obj.get("override_start_date"),
            "override_start_date_check": obj.get("override_start_date_check"),
            "override_end_date": obj.get("override_end_date"),
            "override_end_date_check": obj.get("override_end_date_check"),
            "department_ids": obj.get("department_ids"),
            "estimated_value": obj.get("estimated_value"),
            "estimated_start_date": obj.get("estimated_start_date"),
            "estimated_completion_date": obj.get("estimated_completion_date"),
            "store_number": obj.get("store_number"),
            "accounting_project_number": obj.get("accounting_project_number"),
            "designated_market_area": obj.get("designated_market_area"),
            "erp_integrated": obj.get("erp_integrated") if obj.get("erp_integrated") is not None else False,
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "enable_copy_of_standard_cost_codes": obj.get("enable_copy_of_standard_cost_codes") if obj.get("enable_copy_of_standard_cost_codes") is not None else False
        })
        return _obj


