# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class RestV20CompaniesCompanyIdProjectsProjectIdRequisitionsIdPaymentDetailsPatch400ResponseErrorDetailsInner(BaseModel):
    """
    RestV20CompaniesCompanyIdProjectsProjectIdRequisitionsIdPaymentDetailsPatch400ResponseErrorDetailsInner
    """ # noqa: E501
    reason_code: StrictStr = Field(description="A machine-readable code that identifies the error specifically enough for the client to interpret what happened and take action.")
    message: StrictStr = Field(description="Human readable message")
    source: Optional[StrictStr] = Field(default=None, description="Source of the error")
    __properties: ClassVar[List[str]] = ["reason_code", "message", "source"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestV20CompaniesCompanyIdProjectsProjectIdRequisitionsIdPaymentDetailsPatch400ResponseErrorDetailsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestV20CompaniesCompanyIdProjectsProjectIdRequisitionsIdPaymentDetailsPatch400ResponseErrorDetailsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reason_code": obj.get("reason_code"),
            "message": obj.get("message"),
            "source": obj.get("source")
        })
        return _obj


