# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from procore_sdk.models.rest_v10_projects_project_id_action_plans_plan_items_get200_response_inner_plan_item_assignees_inner import RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInner
from procore_sdk.models.rest_v10_projects_project_id_action_plans_plan_items_get200_response_inner_status import RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerStatus
from typing import Optional, Set
from typing_extensions import Self

class RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInner(BaseModel):
    """
    Action Plan Item (Show)
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="ID")
    plan_item_assignees: Optional[List[RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInner]] = None
    created_at: Optional[StrictStr] = Field(default=None, description="Time the Action Plan Item was created")
    description: Optional[StrictStr] = Field(default=None, description="Description of the Action Plan Item")
    due_at: Optional[datetime] = Field(default=None, description="Due Date of the Action Plan Item")
    holding_type: Optional[StrictStr] = Field(default=None, description="Action Plan Item holding type specifies whether the current item holds all the succeeding items in the section or the plan")
    is_blocked: Optional[StrictBool] = Field(default=None, description="Indicates whether current Action Plan Item is blocked by another Action Plan Item")
    is_blocking: Optional[StrictBool] = Field(default=None, description="Indicates whether current Action Plan Item is blocking other Action Plan Items")
    notes: Optional[StrictStr] = Field(default=None, description="Notes for the Action Plan Item")
    plan_id: Optional[StrictInt] = Field(default=None, description="Plan ID the Action Plan Item belongs to")
    position: Optional[StrictInt] = Field(default=None, description="Position of the Action Plan Item")
    plan_section_id: Optional[StrictInt] = Field(default=None, description="Action Plan Section ID the Item belongs to")
    title: Optional[StrictStr] = Field(default=None, description="Title of the Action Plan Item")
    status: Optional[RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerStatus] = None
    updated_at: Optional[StrictStr] = Field(default=None, description="Time the Action Plan Item was updated")
    __properties: ClassVar[List[str]] = ["id", "plan_item_assignees", "created_at", "description", "due_at", "holding_type", "is_blocked", "is_blocking", "notes", "plan_id", "position", "plan_section_id", "title", "status", "updated_at"]

    @field_validator('holding_type')
    def holding_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['plan', 'section']):
            raise ValueError("must be one of enum values ('plan', 'section')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in plan_item_assignees (list)
        _items = []
        if self.plan_item_assignees:
            for _item_plan_item_assignees in self.plan_item_assignees:
                if _item_plan_item_assignees:
                    _items.append(_item_plan_item_assignees.to_dict())
            _dict['plan_item_assignees'] = _items
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "plan_item_assignees": [RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerPlanItemAssigneesInner.from_dict(_item) for _item in obj["plan_item_assignees"]] if obj.get("plan_item_assignees") is not None else None,
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "due_at": obj.get("due_at"),
            "holding_type": obj.get("holding_type"),
            "is_blocked": obj.get("is_blocked"),
            "is_blocking": obj.get("is_blocking"),
            "notes": obj.get("notes"),
            "plan_id": obj.get("plan_id"),
            "position": obj.get("position"),
            "plan_section_id": obj.get("plan_section_id"),
            "title": obj.get("title"),
            "status": RestV10ProjectsProjectIdActionPlansPlanItemsGet200ResponseInnerStatus.from_dict(obj["status"]) if obj.get("status") is not None else None,
            "updated_at": obj.get("updated_at")
        })
        return _obj


