# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from procore_sdk.models.location import Location
from procore_sdk.models.rest_v10_companies_company_id_workflow_permanent_logs_get200_response_inner_attachments_inner import RestV10CompaniesCompanyIdWorkflowPermanentLogsGet200ResponseInnerAttachmentsInner
from procore_sdk.models.rest_v10_projects_project_id_work_logs_get200_response_inner_created_by import RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy
from typing import Optional, Set
from typing_extensions import Self

class RestV10ProjectsProjectIdDelayLogsGet200ResponseInner(BaseModel):
    """
    RestV10ProjectsProjectIdDelayLogsGet200ResponseInner
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="ID")
    comments: Optional[StrictStr] = Field(default=None, description="Additional comments")
    created_at: Optional[datetime] = Field(default=None, description="Created at")
    var_date: Optional[date] = Field(default=None, description="Date of record", alias="date")
    datetime: Optional[datetime] = Field(default=None, description="Estimated UTC datetime of record")
    delay_type: Optional[StrictStr] = Field(default=None, description="Type of delay")
    deleted_at: Optional[datetime] = Field(default=None, description="Deleted at")
    duration: Optional[StrictInt] = Field(default=None, description="Number of hours the delay lasted (between 1 and 24)")
    end_time: Optional[StrictStr] = Field(default=None, description="Time when the delay ended, Format: HH:MM Example: 21:39")
    end_time_hour: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number between 0 and 23 representing hour of day")
    end_time_minute: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number between 0 and 59 representing minute")
    position: Optional[StrictInt] = Field(default=None, description="Order in which this entry was recorded")
    status: Optional[StrictStr] = Field(default=None, description="Is a log pending or approved")
    start_time_hour: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number between 0 and 23 representing hour of day")
    start_time_minute: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Number between 0 and 59 representing minute")
    updated_at: Optional[datetime] = Field(default=None, description="Updated at")
    created_by: Optional[RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy] = None
    location: Optional[Location] = None
    attachments: Optional[List[RestV10CompaniesCompanyIdWorkflowPermanentLogsGet200ResponseInnerAttachmentsInner]] = Field(default=None, description=":filename to be deprecated, use :name")
    __properties: ClassVar[List[str]] = ["id", "comments", "created_at", "date", "datetime", "delay_type", "deleted_at", "duration", "end_time", "end_time_hour", "end_time_minute", "position", "status", "start_time_hour", "start_time_minute", "updated_at", "created_by", "location", "attachments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestV10ProjectsProjectIdDelayLogsGet200ResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of created_by
        if self.created_by:
            _dict['created_by'] = self.created_by.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestV10ProjectsProjectIdDelayLogsGet200ResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "comments": obj.get("comments"),
            "created_at": obj.get("created_at"),
            "date": obj.get("date"),
            "datetime": obj.get("datetime"),
            "delay_type": obj.get("delay_type"),
            "deleted_at": obj.get("deleted_at"),
            "duration": obj.get("duration"),
            "end_time": obj.get("end_time"),
            "end_time_hour": obj.get("end_time_hour"),
            "end_time_minute": obj.get("end_time_minute"),
            "position": obj.get("position"),
            "status": obj.get("status"),
            "start_time_hour": obj.get("start_time_hour"),
            "start_time_minute": obj.get("start_time_minute"),
            "updated_at": obj.get("updated_at"),
            "created_by": RestV10ProjectsProjectIdWorkLogsGet200ResponseInnerCreatedBy.from_dict(obj["created_by"]) if obj.get("created_by") is not None else None,
            "location": Location.from_dict(obj["location"]) if obj.get("location") is not None else None,
            "attachments": [RestV10CompaniesCompanyIdWorkflowPermanentLogsGet200ResponseInnerAttachmentsInner.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None
        })
        return _obj


