# coding: utf-8

"""
    Procore Rest API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Contact: apisupport@procore.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from procore_sdk.models.normal_view_attachments_inner import NormalViewAttachmentsInner
from procore_sdk.models.normal_view_business_register import NormalViewBusinessRegister
from procore_sdk.models.normal_view_primary_contact import NormalViewPrimaryContact
from procore_sdk.models.rest_v10_vendors_id_get200_response_one_of1_all_of_bidding import RestV10VendorsIdGet200ResponseOneOf1AllOfBidding
from procore_sdk.models.rest_v10_vendors_id_get200_response_one_of1_all_of_bidding_distribution_inner import RestV10VendorsIdGet200ResponseOneOf1AllOfBiddingDistributionInner
from procore_sdk.models.rest_v10_vendors_id_get200_response_one_of1_all_of_business import RestV10VendorsIdGet200ResponseOneOf1AllOfBusiness
from procore_sdk.models.rest_v10_vendors_id_get200_response_one_of1_all_of_contract_signer import RestV10VendorsIdGet200ResponseOneOf1AllOfContractSigner
from procore_sdk.models.rest_v10_vendors_id_get200_response_one_of1_all_of_invoice_contacts_inner import RestV10VendorsIdGet200ResponseOneOf1AllOfInvoiceContactsInner
from procore_sdk.models.rest_v10_vendors_id_get200_response_one_of1_all_of_standard_cost_codes_inner import RestV10VendorsIdGet200ResponseOneOf1AllOfStandardCostCodesInner
from procore_sdk.models.trade import Trade
from typing import Optional, Set
from typing_extensions import Self

class RestV10VendorsIdGet200ResponseOneOf1(BaseModel):
    """
    Vendor Directory View
    """ # noqa: E501
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    abbreviated_name: Optional[StrictStr] = Field(default=None, description="Abbreviated name")
    address: Optional[StrictStr] = Field(default=None, description="Address")
    attachments: Optional[List[NormalViewAttachmentsInner]] = Field(default=None, description="Attachments")
    authorized_bidder: Optional[StrictBool] = Field(default=None, description="Authorized bidder status")
    business: Optional[RestV10VendorsIdGet200ResponseOneOf1AllOfBusiness] = None
    business_id: Optional[StrictStr] = Field(default=None, description="Business id")
    business_phone: Optional[StrictStr] = Field(default=None, description="Business phone")
    business_register: Optional[NormalViewBusinessRegister] = None
    city: Optional[StrictStr] = Field(default=None, description="City")
    company_vendor: Optional[StrictBool] = None
    contract_signer: Optional[RestV10VendorsIdGet200ResponseOneOf1AllOfContractSigner] = None
    country_name: Optional[StrictStr] = None
    created_at: Optional[datetime] = Field(default=None, description="Created at")
    email_address: Optional[StrictStr] = Field(default=None, description="Email address")
    fax_number: Optional[StrictStr] = Field(default=None, description="Fax number")
    is_connected: Optional[StrictBool] = Field(default=None, description="Connected status")
    labor_union: Optional[StrictStr] = Field(default=None, description="Labor union")
    legal_name: Optional[StrictStr] = None
    license_number: Optional[StrictStr] = Field(default=None, description="License number")
    logo: Optional[StrictStr] = Field(default=None, description="Logo url")
    mobile_phone: Optional[StrictStr] = Field(default=None, description="Mobile phone")
    non_union_prevailing_wage: Optional[StrictBool] = Field(default=None, description="Non union prevailing wage status")
    notes: Optional[StrictStr] = Field(default=None, description="Notes")
    prequalified: Optional[StrictBool] = Field(default=None, description="Prequalified status")
    primary_contact: Optional[NormalViewPrimaryContact] = None
    state_code: Optional[StrictStr] = Field(default=None, description="State code (ISO-3166 Alpha-2 format)")
    state_name: Optional[StrictStr] = None
    trade_name: Optional[StrictStr] = Field(default=None, description="Vendor's Trade Name, also known as Doing Business As (DBA).")
    union_member: Optional[StrictBool] = Field(default=None, description="Union member status")
    updated_at: Optional[datetime] = Field(default=None, description="Updated at")
    website: Optional[StrictStr] = Field(default=None, description="Website url")
    zip: Optional[StrictStr] = Field(default=None, description="Zip code")
    invoice_contacts: Optional[List[RestV10VendorsIdGet200ResponseOneOf1AllOfInvoiceContactsInner]] = Field(default=None, description="Invoice Contacts")
    trades: Optional[List[Optional[Trade]]] = Field(default=None, description="Trades")
    standard_cost_codes: Optional[List[RestV10VendorsIdGet200ResponseOneOf1AllOfStandardCostCodesInner]] = None
    bidding: Optional[RestV10VendorsIdGet200ResponseOneOf1AllOfBidding] = None
    bidding_distribution: Optional[List[RestV10VendorsIdGet200ResponseOneOf1AllOfBiddingDistributionInner]] = Field(default=None, description="Bidding Distribution List")
    __properties: ClassVar[List[str]] = ["id", "name", "abbreviated_name", "address", "attachments", "authorized_bidder", "business", "business_id", "business_phone", "business_register", "city", "company_vendor", "contract_signer", "country_name", "created_at", "email_address", "fax_number", "is_connected", "labor_union", "legal_name", "license_number", "logo", "mobile_phone", "non_union_prevailing_wage", "notes", "prequalified", "primary_contact", "state_code", "state_name", "trade_name", "union_member", "updated_at", "website", "zip", "invoice_contacts", "trades", "standard_cost_codes", "bidding", "bidding_distribution"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RestV10VendorsIdGet200ResponseOneOf1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of business
        if self.business:
            _dict['business'] = self.business.to_dict()
        # override the default output from pydantic by calling `to_dict()` of business_register
        if self.business_register:
            _dict['business_register'] = self.business_register.to_dict()
        # override the default output from pydantic by calling `to_dict()` of contract_signer
        if self.contract_signer:
            _dict['contract_signer'] = self.contract_signer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of primary_contact
        if self.primary_contact:
            _dict['primary_contact'] = self.primary_contact.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in invoice_contacts (list)
        _items = []
        if self.invoice_contacts:
            for _item_invoice_contacts in self.invoice_contacts:
                if _item_invoice_contacts:
                    _items.append(_item_invoice_contacts.to_dict())
            _dict['invoice_contacts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in trades (list)
        _items = []
        if self.trades:
            for _item_trades in self.trades:
                if _item_trades:
                    _items.append(_item_trades.to_dict())
            _dict['trades'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in standard_cost_codes (list)
        _items = []
        if self.standard_cost_codes:
            for _item_standard_cost_codes in self.standard_cost_codes:
                if _item_standard_cost_codes:
                    _items.append(_item_standard_cost_codes.to_dict())
            _dict['standard_cost_codes'] = _items
        # override the default output from pydantic by calling `to_dict()` of bidding
        if self.bidding:
            _dict['bidding'] = self.bidding.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in bidding_distribution (list)
        _items = []
        if self.bidding_distribution:
            for _item_bidding_distribution in self.bidding_distribution:
                if _item_bidding_distribution:
                    _items.append(_item_bidding_distribution.to_dict())
            _dict['bidding_distribution'] = _items
        # set to None if abbreviated_name (nullable) is None
        # and model_fields_set contains the field
        if self.abbreviated_name is None and "abbreviated_name" in self.model_fields_set:
            _dict['abbreviated_name'] = None

        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if business_id (nullable) is None
        # and model_fields_set contains the field
        if self.business_id is None and "business_id" in self.model_fields_set:
            _dict['business_id'] = None

        # set to None if business_phone (nullable) is None
        # and model_fields_set contains the field
        if self.business_phone is None and "business_phone" in self.model_fields_set:
            _dict['business_phone'] = None

        # set to None if business_register (nullable) is None
        # and model_fields_set contains the field
        if self.business_register is None and "business_register" in self.model_fields_set:
            _dict['business_register'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if email_address (nullable) is None
        # and model_fields_set contains the field
        if self.email_address is None and "email_address" in self.model_fields_set:
            _dict['email_address'] = None

        # set to None if fax_number (nullable) is None
        # and model_fields_set contains the field
        if self.fax_number is None and "fax_number" in self.model_fields_set:
            _dict['fax_number'] = None

        # set to None if labor_union (nullable) is None
        # and model_fields_set contains the field
        if self.labor_union is None and "labor_union" in self.model_fields_set:
            _dict['labor_union'] = None

        # set to None if license_number (nullable) is None
        # and model_fields_set contains the field
        if self.license_number is None and "license_number" in self.model_fields_set:
            _dict['license_number'] = None

        # set to None if logo (nullable) is None
        # and model_fields_set contains the field
        if self.logo is None and "logo" in self.model_fields_set:
            _dict['logo'] = None

        # set to None if mobile_phone (nullable) is None
        # and model_fields_set contains the field
        if self.mobile_phone is None and "mobile_phone" in self.model_fields_set:
            _dict['mobile_phone'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if primary_contact (nullable) is None
        # and model_fields_set contains the field
        if self.primary_contact is None and "primary_contact" in self.model_fields_set:
            _dict['primary_contact'] = None

        # set to None if state_code (nullable) is None
        # and model_fields_set contains the field
        if self.state_code is None and "state_code" in self.model_fields_set:
            _dict['state_code'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if website (nullable) is None
        # and model_fields_set contains the field
        if self.website is None and "website" in self.model_fields_set:
            _dict['website'] = None

        # set to None if zip (nullable) is None
        # and model_fields_set contains the field
        if self.zip is None and "zip" in self.model_fields_set:
            _dict['zip'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RestV10VendorsIdGet200ResponseOneOf1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "abbreviated_name": obj.get("abbreviated_name"),
            "address": obj.get("address"),
            "attachments": [NormalViewAttachmentsInner.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "authorized_bidder": obj.get("authorized_bidder"),
            "business": RestV10VendorsIdGet200ResponseOneOf1AllOfBusiness.from_dict(obj["business"]) if obj.get("business") is not None else None,
            "business_id": obj.get("business_id"),
            "business_phone": obj.get("business_phone"),
            "business_register": NormalViewBusinessRegister.from_dict(obj["business_register"]) if obj.get("business_register") is not None else None,
            "city": obj.get("city"),
            "company_vendor": obj.get("company_vendor"),
            "contract_signer": RestV10VendorsIdGet200ResponseOneOf1AllOfContractSigner.from_dict(obj["contract_signer"]) if obj.get("contract_signer") is not None else None,
            "country_name": obj.get("country_name"),
            "created_at": obj.get("created_at"),
            "email_address": obj.get("email_address"),
            "fax_number": obj.get("fax_number"),
            "is_connected": obj.get("is_connected"),
            "labor_union": obj.get("labor_union"),
            "legal_name": obj.get("legal_name"),
            "license_number": obj.get("license_number"),
            "logo": obj.get("logo"),
            "mobile_phone": obj.get("mobile_phone"),
            "non_union_prevailing_wage": obj.get("non_union_prevailing_wage"),
            "notes": obj.get("notes"),
            "prequalified": obj.get("prequalified"),
            "primary_contact": NormalViewPrimaryContact.from_dict(obj["primary_contact"]) if obj.get("primary_contact") is not None else None,
            "state_code": obj.get("state_code"),
            "state_name": obj.get("state_name"),
            "trade_name": obj.get("trade_name"),
            "union_member": obj.get("union_member"),
            "updated_at": obj.get("updated_at"),
            "website": obj.get("website"),
            "zip": obj.get("zip"),
            "invoice_contacts": [RestV10VendorsIdGet200ResponseOneOf1AllOfInvoiceContactsInner.from_dict(_item) for _item in obj["invoice_contacts"]] if obj.get("invoice_contacts") is not None else None,
            "trades": [Trade.from_dict(_item) for _item in obj["trades"]] if obj.get("trades") is not None else None,
            "standard_cost_codes": [RestV10VendorsIdGet200ResponseOneOf1AllOfStandardCostCodesInner.from_dict(_item) for _item in obj["standard_cost_codes"]] if obj.get("standard_cost_codes") is not None else None,
            "bidding": RestV10VendorsIdGet200ResponseOneOf1AllOfBidding.from_dict(obj["bidding"]) if obj.get("bidding") is not None else None,
            "bidding_distribution": [RestV10VendorsIdGet200ResponseOneOf1AllOfBiddingDistributionInner.from_dict(_item) for _item in obj["bidding_distribution"]] if obj.get("bidding_distribution") is not None else None
        })
        return _obj


